Repository Azure/communication-ui-library, pull requests merged in 2024-11, with the labels that each got.

#5368 Update Dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-components/src/components/ModalClone/ModalClone.tsx
  packages/react-components/src/components/VideoGallery/FloatingLocalVideo.tsx
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog

#5390 Update rush and allowed upper node version dependency
  common/scripts/install-run-rush.js
  common/scripts/install-run.js
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  rush.json
  tools/custom-eslint-rules/package.json
Labels: breaking-change, does not need changelog

#5381 Updated Datetime tests to make them independent from user's locale
  packages/react-components/src/components/utils/Datetime.test.ts
Labels: does not need changelog

#5392 [Storybook] Concept Theme page styling
  packages/storybook8/stories/Concepts/Theming/Docs.mdx
  packages/storybook8/stories/Concepts/Theming/index.stories.tsx
Labels: does not need changelog

#5362 Call Features Stream Util Implementation and Call client state for Together mode feature
  change-beta/@azure-communication-react-588b7294-cdfe-4c6c-8fea-6019b28165aa.json
  change-beta/@azure-communication-react-fccab07a-9214-4608-9852-dde7be8f0087.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallFeatureStreamUtils.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/InternalCallContext.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/StreamUtils.ts
  packages/calling-stateful-client/src/TogetherModeSubscriber.ts
  packages/calling-stateful-client/src/TogetherModeVideoStreamSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: breaking-change

#5389 Storybook documentation on pivoting a call end screen
  packages/storybook8/stories/Composites/CallComposite/Docs.mdx
Labels: does not need changelog

#5347 Integrate Teams meeting hard mute feature part 1 - stateful client changes
  change-beta/@azure-communication-react-2320b89c-a8ee-4bc1-a2b5-d9fc28bea0af.json
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/MediaAccessSubscriber.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#5383 Integrate Teams meeting hard mute feature part 2 - component bindings
  change-beta/@azure-communication-react-3a488a89-5800-4662-8e1e-1a11ccc3aa44.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/participantListSelector.ts
  packages/calling-component-bindings/src/utils/participantListSelectorUtils.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/types/ParticipantListParticipant.ts
  packages/react-components/src/types/VideoGalleryParticipant.ts
Labels: breaking-change

#5396 Bump all GitHub action dependencies for Node20 breaking change alert
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-api-view-feature-level.yml
  .github/workflows/deploy-azure-webapps.yml
  .github/workflows/deploy-feature-azure-webapps.yml
  .github/workflows/deploy-release-azure-webapps.yml
  .github/workflows/npm-release-publish.yml
  .github/workflows/publish-chromatic.yml
  .github/workflows/stress-test-ui-tests.yml
  .github/workflows/update-chat-snapshots.yml
  .github/workflows/update-snapshots.yml
Labels: does not need changelog

#5404 [storybook8] Update getting started page to better reflect what is present in our quickstarts
  packages/storybook8/stories/Composites/GettingStarted.mdx
  packages/storybook8/stories/Composites/snippets/QuickstartCompositeAdapter.snippet.tsx
  packages/storybook8/stories/Composites/snippets/QuickstartCompositeComplete.snippet.tsx
Labels: does not need changelog

#5401 [Reactions] export reactions button in stable
  change-beta/@azure-communication-react-99197026-65db-49f7-8af0-394f35f01a71.json
  change/@azure-communication-react-99197026-65db-49f7-8af0-394f35f01a71.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ReactionButton.tsx
  packages/react-components/src/components/index.ts
Labels: breaking-change

#5385 Cnwankwo/together_mode_api
  change-beta/@azure-communication-react-c495d5e5-3d35-4714-a329-a839d316e765.json
  change-beta/@azure-communication-react-e603fe15-0458-47d3-9c1a-4dbb2da470dd.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/types/TogetherModeTypes.ts
  packages/react-components/src/types/index.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
Labels: breaking-change

#5405 Add es-MX and fr-CA locales. Get latest strings
  change-beta/@azure-communication-react-02055a40-2832-4cfa-9d32-ae1a1dc922ad.json
  change/@azure-communication-react-02055a40-2832-4cfa-9d32-ae1a1dc922ad.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/ComponentLocale.tsx
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/ComponentLocale.tsx
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/index.ts
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/es-MX/CompositeLocale.tsx
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/CompositeLocale.tsx
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
  packages/storybook8/stories/Concepts/Localization/Docs.mdx
  packages/storybook8/stories/locales.ts
Labels: breaking-change

#5410 Groom changelog stable remove beta suffix/1.21.0
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#5407 Update @azure/communication-calling to 1.31.2-beta.1 and `@azure/communication-calling-effects` to 1.1.2
  change-beta/@azure-communication-react-9feaa64e-c9a2-4735-bcb4-4575f297e9b8.json
  change-beta/@azure-communication-react-f238271e-67ab-425c-9992-fe015c0f720b.json
  change/@azure-communication-react-9feaa64e-c9a2-4735-bcb4-4575f297e9b8.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: significant bundle size change

#5412 [Storybook] Updating the title of links as per feedback
  packages/storybook8/stories/Composites/GettingStarted.mdx
Labels: does not need changelog

#5413 [Storybook] Updating the MSDocs link
  packages/storybook8/stories/Composites/GettingStarted.mdx
Labels: does not need changelog

#5417 [release] TDBuild latest localization
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
Labels: does not need changelog

#5418 Updated release documentation to include Storybook bug bash
  docs/releases/creating-a-release.md
Labels: does not need changelog

#5420 Updated patch versions of FluentUI dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-javascript-loaders/package.json
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog, significant bundle size change

#5427 Fix A11y Properties of Participant List
  change-beta/@azure-communication-react-7155bada-4e58-429e-9872-ff86e027002e.json
  change/@azure-communication-react-7155bada-4e58-429e-9872-ff86e027002e.json
  packages/acs-ui-common/src/localizationUtils.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/common/AddPeopleDropdown.tsx
  packages/react-composites/src/composites/common/ParticipantContainer.tsx
  packages/react-composites/src/composites/common/SidePaneHeader.tsx
Labels: significant bundle size change

#5426 Fix: `Uncaught SyntaxError: Illegal return statement`
  samples/CallWithChat/public/index.html
  samples/Calling/public/index.html
  samples/Chat/public/index.html
Labels: does not need changelog

#5435 Update dependencies
  common/config/rush/pnpm-lock.yaml
Labels: does not need changelog

#5323 Onfetchavatarpersonadata should allow returning undefined
  change-beta/@azure-communication-react-8bf89ac1-247e-4f57-9d87-6ea2a543ef0a.json
  change/@azure-communication-react-8bf89ac1-247e-4f57-9d87-6ea2a543ef0a.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/common/AvatarPersona.tsx
Labels: breaking-change

#5439 Update deps for auto installer rush prettier
  common/autoinstallers/rush-prettier/pnpm-lock.yaml
Labels: does not need changelog

#5447 Update cross-spawn to 7.0.6
  common/config/rush/variants/stable/pnpm-lock.yaml
Labels: does not need changelog

#5446 Use a github repo variable to dictate the ubuntu version runners run on
  .github/workflows/alpha-release.yml
  .github/workflows/breaking-change-check.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-api-view-feature-level.yml
  .github/workflows/create-prerelease-branch.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/deploy-azure-webapps.yml
  .github/workflows/deploy-feature-azure-webapps.yml
  .github/workflows/deploy-release-azure-webapps.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/nightly-cd.yml
  .github/workflows/npm-release-publish.yml
  .github/workflows/publish-chromatic.yml
  .github/workflows/stress-test-ui-tests.yml
  .github/workflows/update-api-files.yml
  .github/workflows/update-chat-snapshots.yml
  .github/workflows/update-snapshots.yml
Labels: does not need changelog
