Repository Azure/communication-ui-library, pull requests merged in 2024-04, with the labels that each got.

#4330 End call experience
  change-beta/@azure-communication-react-0f389b9e-b745-4790-ba77-f0da0fca8ec7.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/EndCallButton.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/components/Prompt.tsx
  packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
  packages/react-composites/src/composites/common/utils.tsx
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallCompositeContainer.tsx
Labels: breaking-change

#4374 [Calling][Refactor]Remove pptlive beta
  change-beta/@azure-communication-react-a7122a70-c861-4ec3-9524-de8f6510dbd4.json
  change/@azure-communication-react-a7122a70-c861-4ec3-9524-de8f6510dbd4.json
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
Labels: breaking-change

#4368 [Calling] Changing the order of the reaction animation appearance.
  change-beta/@azure-communication-react-93873c46-8b39-4be2-9f19-e2564d98fcfc.json
  change/@azure-communication-react-93873c46-8b39-4be2-9f19-e2564d98fcfc.json
  packages/react-components/src/components/ReactionButton.tsx
Labels: bug

#4366 [Chat][File Sharing] Refactor File Sharing Upload Flow
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/AttachmentCard.test.tsx
  packages/react-components/src/components/AttachmentCard.tsx
  packages/react-components/src/components/AttachmentUploadCards.test.tsx
  packages/react-components/src/components/AttachmentUploadCards.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.test.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-components/src/components/utils/common.ts
  packages/react-components/src/types/Attachment.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.test.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationFileUploadAdapter.test.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationFileUploadAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapterProvider.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUploadButton.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/src/composites/ChatComposite/selectors/attachmentUploadsSelector.ts
  packages/react-composites/src/composites/ChatComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/ChatComposite/selectors/fileUploadsSelector.ts
  packages/react-composites/src/composites/common/SendBox.tsx
  packages/react-composites/src/index.ts
  packages/react-composites/src/mocks/FakeChatAdapterArgs.ts
  packages/react-composites/tests/app/chat/FakeAdapterApp.tsx
  packages/react-composites/tests/app/chat/LiveTestApp.tsx
  packages/react-composites/tests/browser/chat/hermetic/AttachmentSharing.test.ts
  packages/storybook/stories/CallWithChatComposite/CallWithChatCompositeDocs.tsx
  packages/storybook/stories/INTERNAL/RTE/RTESendBox.stories.tsx
  packages/storybook/stories/INTERNAL/RTE/snippets/RTEAttachmentUploads.snippet.tsx
  packages/storybook/stories/SendBox/SendBox.stories.tsx
  packages/storybook/stories/SendBox/snippets/AttachmentUploads.snippet.tsx
Labels: breaking-change

#4370 [Calling] Reaction bug for animation inconsistency for presentation mode reaction burst case fixed
  change-beta/@azure-communication-react-83fbcf28-2844-46d4-8e21-d726a0f1976a.json
  change/@azure-communication-react-83fbcf28-2844-46d4-8e21-d726a0f1976a.json
  packages/react-components/src/components/VideoGallery/RemoteContentShareReactionOverlay.tsx
  packages/react-components/src/components/styles/ReactionOverlay.style.ts
Labels: bug

#4380 Dismiss drawer on reaction click on mobile
  change-beta/@azure-communication-react-3935fb13-4c4e-4bd3-ba99-6f85af368223.json
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
Labels: bug

#4410 [Calling][Refactor] Bump Calling SDK stable version
  change-beta/@azure-communication-react-4479b7d2-ebdb-429b-b2da-a1a7a78ab387.json
  change/@azure-communication-react-4479b7d2-ebdb-429b-b2da-a1a7a78ab387.json
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change, dependencies, call composite

#4409 [Calling] Allowing capability changes only in connected screen
  change-beta/@azure-communication-react-d35cbdfd-82d1-45d4-b835-c272ff2272c9.json
  change/@azure-communication-react-d35cbdfd-82d1-45d4-b835-c272ff2272c9.json
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
Labels: bug

#4412 [Calling] Solving reaction out of screen viewport issue
  change-beta/@azure-communication-react-0fde03e9-dcee-4347-8321-a90d9d81da03.json
  change/@azure-communication-react-0fde03e9-dcee-4347-8321-a90d9d81da03.json
  packages/react-components/src/components/VideoGallery/RemoteContentShareReactionOverlay.tsx
Labels: bug

#4406 [Chat][FileSharing] Add A11y for FluentUI attachment card
  change-beta/@azure-communication-react-a5a21ca4-95a1-4fa8-a16f-cd33c3a6d4e1.json
  change/@azure-communication-react-a5a21ca4-95a1-4fa8-a16f-cd33c3a6d4e1.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/AttachmentCard.tsx
  packages/react-components/src/components/AttachmentUploadCards.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/styles/AttachmentCard.styles.ts
  packages/react-components/src/components/utils/common.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
Labels: breaking-change

#4415 Promote spotlight to GA
  change-beta/@azure-communication-react-60500e27-ef4e-44c3-8612-00f90374dfe1.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/participantListSelector.ts
  packages/calling-component-bindings/src/utils/participantListSelectorUtils.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/types/ParticipantListParticipant.ts
  packages/react-composites/src/composites/CallComposite/components/Prompt.tsx
Labels: breaking-change

#4427 [Calling][Feature] Move PPTLive to stable
  change-beta/@azure-communication-react-3faafb86-ef71-44fa-bd9e-68e34d20a5cb.json
  change/@azure-communication-react-3faafb86-ef71-44fa-bd9e-68e34d20a5cb.json
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
Labels: breaking-change

#4381 CaptionsKindChanged event
  change-beta/@azure-communication-react-149ee832-c93d-4fbb-bb74-72c04d88915b.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/CaptionsSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/CaptionsBanner.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/Drawer/PreparedMoreDrawer.tsx
  packages/react-composites/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts
  packages/react-composites/tests/browser/common/constants.ts
Labels: breaking-change

#4474 [Chat] Updated Upload Options
  change-beta/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json
  change/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/types/Attachment.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/tests/app/chat/FakeAdapterApp.tsx
  packages/react-composites/tests/app/chat/LiveTestApp.tsx
  samples/Chat/src/app/utils/uploadHandler.ts
Labels: breaking-change

#4465 [Chat] Deprecate Upload Manager
  change-beta/@azure-communication-react-1236f53c-7c4a-4856-a126-44af56c64174.json
  change-beta/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json
  change/@azure-communication-react-1236f53c-7c4a-4856-a126-44af56c64174.json
  change/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/types/Attachment.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.test.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapterProvider.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/tests/app/chat/FakeAdapterApp.tsx
  packages/react-composites/tests/app/chat/LiveTestApp.tsx
  samples/Chat/src/app/utils/uploadHandler.ts
Labels: breaking-change

#4477 [Chat] Make UploadAdapter Internal
  change-beta/@azure-communication-react-215b2b2c-0df6-49aa-95d5-12a7d0884824.json
  change/@azure-communication-react-215b2b2c-0df6-49aa-95d5-12a7d0884824.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapterProvider.tsx
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/src/composites/ChatComposite/selectors/baseSelectors.ts
  packages/storybook/stories/Adapters/Adapters.stories.mdx
Labels: breaking-change

#4484 Ruslanz/meeting id samples with set
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/ChatButton/useUnreadMessagesTracker.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/index.ts
Labels: breaking-change

#4492 [OCE] Bump Chat SDK Version
  change/@azure-communication-react-828c0e54-29a2-4fd1-ab6b-bc8dbf892488.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/chat-stateful-client/src/ChatClientState.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/fake-backends/package.json
  packages/fake-backends/src/FakeChatThreadClient.ts
  packages/react-composites/package.json
  packages/react-composites/src/composites/ChatComposite/adapter/StubChatClient.ts
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change

#4464 [Chat] File Sharing Refactor
  change-beta/@azure-communication-react-7f8f9b0e-279a-4976-bf03-6a22f90ee4a1.json
  change/@azure-communication-react-7f8f9b0e-279a-4976-bf03-6a22f90ee4a1.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/AttachmentCard.tsx
  packages/react-components/src/components/AttachmentUploadCards.test.tsx
  packages/react-components/src/components/AttachmentUploadCards.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/SendBoxErrors.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-components/src/types/Attachment.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.test.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationAttachmentUploadAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapterProvider.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUploadButton.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/src/composites/ChatComposite/selectors/baseSelectors.ts
  packages/react-composites/tests/app/chat/FakeAdapterApp.tsx
  packages/react-composites/tests/app/chat/LiveTestApp.tsx
  packages/storybook/stories/Adapters/Adapters.stories.mdx
  packages/storybook/stories/INTERNAL/RTE/RichTextSendBox.stories.tsx
  packages/storybook/stories/INTERNAL/RTE/snippets/RichTextSendBoxAttachmentUploads.snippet.tsx
  packages/storybook/stories/SendBox/SendBox.stories.tsx
  packages/storybook/stories/SendBox/snippets/AttachmentUploads.snippet.tsx
  samples/Chat/src/app/utils/uploadHandler.ts
  samples/Server/appsettings.json.sample
Labels: breaking-change

#4522 [Release changelog improvement] Do not need to commit a changelog if the changes does not affect published packages. Remove None type
  .github/workflows/ci.yml
  change-beta/@azure-communication-react-ecf28197-1fbd-4a50-b1e7-6f284e429bec.json
  change-beta/@azure-communication-react-f7a27f45-f6ee-4fe9-b706-10a0980ae8cd.json
  change/@azure-communication-react-09025757-4ceb-4db0-b80b-d32a16b6a853.json
  change/@azure-communication-react-0a46c31a-f8b8-451a-b42f-360147feb7d5.json
  change/@azure-communication-react-0b4ac28e-db8e-41f4-a939-4f1a29689812.json
  change/@azure-communication-react-29e7fcaa-9de4-4999-9ddf-396f9c974816.json
  change/@azure-communication-react-364af351-f5b9-4e97-b257-407a39303887.json
  change/@azure-communication-react-43827df3-34e1-47ec-85d8-ac017671a641.json
  change/@azure-communication-react-47ad9233-ee0b-405b-a7d2-e62a003c6f3f.json
  change/@azure-communication-react-4f36abc0-bc2f-42cf-a095-b8015c5e7607.json
  change/@azure-communication-react-52bb94c8-240b-4290-a9bd-8a4bb6dcc16f.json
  change/@azure-communication-react-597b8fd4-4f78-401e-b5ca-e86152139268.json
  change/@azure-communication-react-59b33420-ac00-49a6-8e82-f68968388e3c.json
  change/@azure-communication-react-63d24220-0d35-49e1-98d9-43cda6e64640.json
  change/@azure-communication-react-6ba86513-f414-46f0-9070-30e17038734b.json
  change/@azure-communication-react-7332768d-224e-4d3a-969b-4894509a690b.json
  change/@azure-communication-react-7ca37d86-390f-46ed-b2e5-0f4a2b9f7d3b.json
  change/@azure-communication-react-822d1d28-ec07-459a-838e-b38cb01d5e5f.json
  change/@azure-communication-react-828c0e54-29a2-4fd1-ab6b-bc8dbf892488.json
  change/@azure-communication-react-89a13d96-f656-4b47-b00a-55f9666e2ae6.json
  change/@azure-communication-react-8b2cb719-c74e-4f00-853b-2cac906187c0.json
  change/@azure-communication-react-8d09f8de-3dea-4b92-942f-308737668be5.json
  change/@azure-communication-react-8de56817-f1e6-4d86-834e-3a1e89eec6d7.json
  change/@azure-communication-react-8f689a76-d154-4ffe-a84b-0d5e831b5dfe.json
  change/@azure-communication-react-9fe5a6f8-6d78-41cb-9efb-d85013b805c1.json
  change/@azure-communication-react-a53b1b4d-d385-4dec-b16d-ef05f81ed38a.json
  change/@azure-communication-react-a62f2f10-58ee-4cca-b6e8-80f0fe092edc.json
  change/@azure-communication-react-b13010d5-a240-4452-81e7-01aefadef278.json
  change/@azure-communication-react-bb221623-4baf-4501-bf5e-d994e842aee7.json
  change/@azure-communication-react-cf02895f-28af-4425-ad05-042fb83f20cd.json
  change/@azure-communication-react-ebeb96cc-561b-4ab9-94b4-7db0173c04d8.json
  change/@azure-communication-react-ff7297f2-35c6-4cf4-a173-032a0c41a9ba.json
  common/config/beachball/changelog-config.ts
  common/scripts/changelog/change.mjs
  common/scripts/changelog/changelog.mjs
  common/scripts/changelog/check.mjs
Labels: do not need changelog

#4532 Remove changelog None type
  change/@azure-communication-react-56131719-373c-46ba-8eb7-f243e21498c8.json
  change/@azure-communication-react-fd4c3b03-99a0-4eaa-acfc-7161f0645cd0.json
Labels: do not need changelog

#4344 Update CallWithChat chat adapter to act synchronously. Add MeetingId&Passcode option to samples
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/ChatButton/useUnreadMessagesTracker.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.test.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/index.ts
  samples/CallWithChat/src/app/App.tsx
  samples/CallWithChat/src/app/utils/AppUtils.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/Calling/src/app/App.tsx
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: breaking-change

#4533 [OCE] Calling stable sdk updates
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/calling-stateful-client/src/CallAgentDeclarative.test.ts
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: do not need changelog

#4544 Add documentation to indicate the RTE edit box doesn't support mention
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
Labels: do not need changelog

#4541 [Chat] Add UI tests for RichTextEditBox
  packages/react-components/tests/browser/ChatMessageComponentAsEditBox.spec.tsx
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4529 [Chat] Add UI tests for RichTextSendBox
  packages/react-components/playwright/index.tsx
  packages/react-components/tests/browser/ChatMessageComponentAsEditBox.spec.tsx
  packages/react-components/tests/browser/RichTextSendBox.spec.tsx
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-disabled-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-disabled-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-disabled-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-hover-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-hover-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-hover-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-without-format-toolbar-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4535 fix case when passcode was lost
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: do not need changelog

#4552 [Chat]Add feature flag for RTE composite and image upload
  common/config/babel/features.js
Labels: do not need changelog
