Repository Azure/communication-ui-library, pull requests merged in 2024-08, with the labels that each got.

#4974 [Chat] Remove component dependency on inlineImages and rename APIs
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.test.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/UpdateContentPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
  packages/react-composites/src/composites/common/constants.ts
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook/stories/MessageThread/snippets/WithRichTextEditorInlineImages.snippet.tsx
  packages/storybook/stories/SendBox/RichTextSendBox.stories.tsx
  packages/storybook/stories/SendBox/snippets/RichTextSendBoxWithInlineImages.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/Docs.mdx
  packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditorInlineImages.snippet.tsx
Labels: breaking-change, does not need changelog

#5000 [Chat]Get image file name for redo images
  packages/acs-ui-common/src/constants.ts
  packages/acs-ui-common/src/index.ts
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/common/constants.ts
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook/stories/SendBox/RichTextSendBox.stories.tsx
  packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
Labels: breaking-change

#4990 [RTE] Added undo and redo handling for inline images
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/UndoRedoPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
Labels: does not need changelog

#4945 Storybook 8 migration captions
  packages/storybook8/stories/Concepts/ClosedCaptions/Doc.mdx
  packages/storybook8/stories/Concepts/ClosedCaptions/snippets/ClosedCaptions.snippet.tsx
Labels: does not need changelog

#4996 minor updates
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
Labels: does not need changelog

#5005 [Storybook 8] Concepts/Rooms Page
  packages/storybook8/stories/Concepts/Rooms/Docs.mdx
  packages/storybook8/stories/Concepts/Rooms/snippets/RoomsCall.snippet.tsx
Labels: does not need changelog

#4981 Enable local screenshare stream
  change-beta/@azure-communication-react-5961c905-62a5-426d-a39e-cded181d70ab.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/LocalScreenShare.tsx
  packages/react-components/src/components/VideoGallery/RemoteScreenShare.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/types/VideoGalleryParticipant.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/Screenshare.test.ts-snapshots/local-screenshare-Mobile-Android-Portrait-linux.png
Labels: breaking-change

#4960 Alkwa/interop conceptual docs
  packages/storybook8/public/images/teams-get-meeting-link.png
  packages/storybook8/public/images/teams-get-meetingid-and-passcode.png
  packages/storybook8/stories/Concepts/TeamsInterop/ComplianceBanner/ComplianceBanner.story.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/ComplianceBanner/Docs.mdx
  packages/storybook8/stories/Concepts/TeamsInterop/ComplianceBanner/index.stories.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/ComplianceBanner/snippets/CallComponent.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/ComplianceBanner/snippets/ComplianceBanner.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithLink/Docs.mdx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithLink/JoinMeetingWithLink.story.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithLink/index.stories.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithLink/snippets/CallWithChat.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithLink/snippets/CallWithChatWithErrorChecks.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithMeetingId/Docs.mdx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithMeetingId/JoinMeetingWithMeetingId.story.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithMeetingId/index.stories.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithMeetingId/snippets/CallWithChat.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/JoinMeetingWithMeetingId/snippets/CallWithChatWithErrorChecks.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/Lobby/Docs.mdx
  packages/storybook8/stories/Concepts/TeamsInterop/Lobby/Lobby.story.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/Lobby/index.stories.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/Lobby/snippets/Lobby.snippet.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/utils/CompositeStringUtils.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/utils/Utils.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/utils/controlsUtils.ts
  packages/storybook8/stories/Concepts/constants.ts
  packages/storybook8/stories/Feedback.mdx
  packages/storybook8/stories/Overview.mdx
Labels: documentation, does not need changelog

#4943 Add and subscribe remote ufd data to stateful client
  change-beta/@azure-communication-react-91d0ce60-c15a-4675-a705-c049f6a1f4ba.json
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/UserFacingDiagnosticsSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#5014 [Release] Update Snapshots
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/default-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/speaker-layout-Desktop-Chrome-linux.png
Labels: does not need changelog

#4982 Example pages for LocalPreview, DeviceSettings, TeamsTheme, and Incoming Call Toast/Modal
  packages/storybook8/stories/Examples/DeviceSettings/DeviceSettingsDropDown.story.tsx
  packages/storybook8/stories/Examples/DeviceSettings/Docs.mdx
  packages/storybook8/stories/Examples/DeviceSettings/index.stories.tsx
  packages/storybook8/stories/Examples/DeviceSettings/snippets/DeviceSettingsDropdown.snippet.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallModal/Docs.mdx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallModal/IncomingCallModal.story.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallModal/index.stories.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallModal/snippets/exampleIncomingCallModal.snippet.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallToast/Docs.mdx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallToast/IncomingCallToast.story.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallToast/index.stories.tsx
  packages/storybook8/stories/Examples/IncomingCallAlerts/IncomingCallToast/snippets/exampleIncomingCallToast.snippet.tsx
  packages/storybook8/stories/Examples/LocalPreview/Docs.mdx
  packages/storybook8/stories/Examples/LocalPreview/LocalPreview.story.tsx
  packages/storybook8/stories/Examples/LocalPreview/index.stories.tsx
  packages/storybook8/stories/Examples/LocalPreview/snippets/LocalPreviewExample.snippet.tsx
  packages/storybook8/stories/Examples/Themes/Docs.mdx
  packages/storybook8/stories/Examples/Themes/TeamsTheme.story.tsx
  packages/storybook8/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot
  packages/storybook8/stories/Examples/Themes/index.stories.tsx
  packages/storybook8/stories/Examples/Themes/snippets/TeamsTheme.snippet.tsx
Labels: documentation, does not need changelog

#5015 [Localization] Update strings
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5023 [Storybook8] Migrate INTERNAL components for video effects
  packages/storybook8/stories/INTERNAL/VideoEffects/Docs.mdx
  packages/storybook8/stories/INTERNAL/VideoEffects/VideoEffects.story.tsx
  packages/storybook8/stories/INTERNAL/VideoEffects/index.stories.tsx
  packages/storybook8/stories/INTERNAL/VideoEffects/snippets/SelectableVideoEffects.snippet.tsx
  packages/storybook8/stories/INTERNAL/VideoEffects/snippets/VideoBackgroundEffectsPicker.snippet.tsx
Labels: documentation, does not need changelog

#5027 Fix bug in Call With Chat storybook preview stuck when args changes
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/storybook/stories/CallWithChatComposite/snippets/CallWithChatWithErrorChecks.snippet.tsx
Labels: does not need changelog

#5028 Fix bug in storybook to include teams meeting short link
  packages/storybook/stories/CallComposite/snippets/CTEContainer.snippet.tsx
  packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx
  packages/storybook/stories/CallComposite/snippets/CustomDataModelExampleContainer.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/CustomButtonWithAsyncStateText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/CustomButtonWithStateText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/LegacyControlBarCustomButtonInjectionText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/MobileCustomButtonInjectionText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/OverflowCustomButtonInjectionText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/PrimaryCustomButtonInjectionText.snippet.tsx
  packages/storybook/stories/CustomButtonInjection/snippets/SecondaryCustomButtonInjectionText.snippet.tsx
  packages/storybook/stories/snippets/localization/LocalizedComposites.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/snippets/CTEContainer.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/snippets/Container.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/snippets/CustomDataModelExampleContainer.snippet.tsx
  packages/storybook8/stories/Concepts/Localization/snippets/LocalizedComposites.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/CustomButtonWithAsyncStateText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/CustomButtonWithStateText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/LegacyControlBarCustomButtonInjectionText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/MobileCustomButtonInjectionText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/OverflowCustomButtonInjectionText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/PrimaryCustomButtonInjectionText.snippet.tsx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/SecondaryCustomButtonInjectionText.snippet.tsx
Labels: does not need changelog

#4494 [Calling] Expose PPTLive presenter information
  change-beta/@azure-communication-react-3b3192c0-d7bb-47d8-bb4b-b80146fe9a3b.json
  change/@azure-communication-react-3b3192c0-d7bb-47d8-bb4b-b80146fe9a3b.json
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/PPTLiveSubscriber.ts
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/RemoteScreenShare.tsx
  packages/react-components/src/components/VideoTile.tsx
Labels: breaking-change

#5009 Add join breakout room button and leave room/leave meeting menu buttons
  change-beta/@azure-communication-react-1f30d324-eb3e-4edd-a772-abed0a7d686d.json
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/EndCallButton.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#5041 [Storybook8] Migrate 1:N call composite page
  packages/storybook8/stories/Composites/CallComposite/1ton/Docs.mdx
  packages/storybook8/stories/Composites/CallComposite/1ton/Start1toN.story.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/components/IncomingCallAlerts.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/components/SimpleCallScreen.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/components/SimpleInboundHomeScreen.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/index.stories.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Container1toNInbound.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Container1toNOutbound.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Quickstart1ToN.snippet.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Utils.tsx
Labels: documentation, does not need changelog

#5042 [Storybook8] Migrate compliance banner to v8
  packages/storybook8/stories/INTERNAL/ComplianceBanner/ComplianceBanner.story.tsx
  packages/storybook8/stories/INTERNAL/ComplianceBanner/Docs.mdx
  packages/storybook8/stories/INTERNAL/ComplianceBanner/index.stories.tsx
  packages/storybook8/stories/INTERNAL/ComplianceBanner/snippets/ComplianceBanner.snippet.tsx
Labels: documentation, does not need changelog

#5043 [Storybook8] Migrate captions banner to v8
  packages/storybook8/stories/INTERNAL/CaptionsBanner/CaptionsBanner.story.tsx
  packages/storybook8/stories/INTERNAL/CaptionsBanner/Docs.mdx
  packages/storybook8/stories/INTERNAL/CaptionsBanner/index.stories.tsx
  packages/storybook8/stories/INTERNAL/CaptionsBanner/mockCaptions.ts
  packages/storybook8/stories/INTERNAL/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
Labels: documentation, does not need changelog

#4977 Added latest notifications to CallClientState for breakout rooms notifications
  change-beta/@azure-communication-react-6c23c026-bccd-430b-9be2-872be3a3c363.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.test.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/adapters.ts
  packages/react-composites/src/composites/index.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: breaking-change

#5051 Update communication calling to 1.28.1-beta.4 and 1.27.5
  change-beta/@azure-communication-react-74563221-eef7-4d5a-ad93-71af47706da1.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change

#5048 Timed breakout rooms and 2 new notifications
  change-beta/@azure-communication-react-44ebece8-6ea4-4f2b-8089-71647c34f717.json
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useCompositeStringsForNotificationStack.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/ControlBar/Timer.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#5057 Fix missing PR links in changelogs - Update to use new `changeDir` option in beachball
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/changelog/change.mjs
  common/scripts/changelog/changelog.mjs
  common/scripts/changelog/check.mjs
  common/scripts/changelog/collect.mjs
  common/scripts/changelog/constants.mjs
Labels: does not need changelog

#5060 [VideoStreamAvailable] remove stream available cc comment
  common/config/babel/features.js
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/RemoteVideoStreamSubscriber.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
Labels: does not need changelog

#5061 Remove notifications cc
  common/config/babel/features.js
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/communication-react/src/index.ts
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/HoldPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/TransferPage.tsx
  packages/react-composites/src/composites/CallComposite/types/ErrorTracking.ts
  packages/react-composites/src/composites/CallComposite/utils/TrackErrors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
Labels: does not need changelog

#5059 Add mobile banner for breakout rooms and handle scenario of being unassigned from breakout room
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/Banner.tsx
  packages/react-composites/src/composites/CallComposite/components/BreakoutRoomsBanner.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
Labels: breaking-change

#5073 [Incoming Calls] API updates
  change-beta/@azure-communication-react-8d95fc61-8d3e-4f89-8e40-ad3363e8faac.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/incomingCallStackSelector.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/HoldButton.tsx
  packages/react-components/src/components/IncomingCallStack.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/HoldPane.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/common/AddPeopleButton.tsx
  packages/react-composites/src/composites/common/AddPeopleDropdown.tsx
  packages/react-composites/src/composites/common/CallingDialpad.tsx
  packages/react-composites/src/composites/common/CalloutWithIcon.tsx
  samples/Calling/src/app/views/CallScreen.tsx
Labels: breaking-change

#5062 [DNS] Adapter API changes and common calling handlers
  change-beta/@azure-communication-react-1af4c039-3991-4a9f-af3d-c85447155e6a.json
  change/@azure-communication-react-1af4c039-3991-4a9f-af3d-c85447155e6a.json
  common/config/babel/features.js
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-composites/package.json
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/createHandlers.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.ts
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependencyLazy.ts
  packages/react-composites/src/composites/index.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallScreen.tsx
Labels: breaking-change

#4567 Support HMR for codespaces development in our test apps
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/config/webpack/sampleapp.webpack.config.js
  samples/Server/package.json
Labels: does not need changelog

#4935 [inbound calling] incoming call conceptual docs
  packages/storybook/stories/INTERNAL/IncomingCallNotification/InboundCalling.stories.mdx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/IncomingCallNotification.stories.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/IncomingCallStack.stories.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/snippets/IncomingCallNotificationStyling.snippet.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/snippets/IncomingCallStack.snippet.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/snippets/IncomingCallStackPropsExample.snippet.tsx
  packages/storybook/stories/controlsUtils.ts
Labels: documentation, storybook, does not need changelog

#5094 [Inbound Calling] Move stories out of internal
  packages/storybook/stories/IncomingCallNotification/InboundCalling.stories.mdx
  packages/storybook/stories/IncomingCallNotification/IncomingCallNotification.stories.tsx
  packages/storybook/stories/IncomingCallNotification/IncomingCallStack.stories.tsx
  packages/storybook/stories/IncomingCallNotification/snippets/IncomingCallNotification.snippet.tsx
  packages/storybook/stories/IncomingCallNotification/snippets/IncomingCallNotificationStyling.snippet.tsx
  packages/storybook/stories/IncomingCallNotification/snippets/IncomingCallStack.snippet.tsx
  packages/storybook/stories/IncomingCallNotification/snippets/IncomingCallStackPropsExample.snippet.tsx
Labels: does not need changelog
