Repository Azure/communication-ui-library, pull requests merged in 2024-05, with the labels that each got.

#4547 GA endcall experience GA
  common/config/babel/features.js
  packages/communication-react/review/stable/communication-react.api.md
Labels: breaking-change

#4553 Update meeting Id join to stable
  change/@azure-communication-react-a6be18c4-8750-497c-98ff-f509be659bf7.json
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: breaking-change

#4573 [bugfix][a11y] Add aria labels for people button on selected and unselected
  change-beta/@azure-communication-react-d1a069f1-424a-4222-8d40-6e4eaa950e82.json
  change/@azure-communication-react-d1a069f1-424a-4222-8d40-6e4eaa950e82.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#4570 Update Strings for main
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: do not need changelog

#4575 delete bad changelog
  change/@azure-communication-react-5e86ae5b-6832-4e90-ad70-0d8f6d1a23a2.json
Labels: do not need changelog

#4572 [RTE] Rooster component and some plugins migration
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.test.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/InputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/KeyboardInputPlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/PlaceholderPlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/UpdateContentPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/tests/browser/ChatMessageComponentAsEditBox.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponent.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponentTablesTests.spec.tsx
  packages/react-components/tests/browser/RichTextInsertTablePane.spec.tsx
  packages/react-components/tests/browser/RichTextSendBox.spec.tsx
Labels: do not need changelog

#4569 [Chat] Add loading and broken image hermetic tests for inline image and ImageOverlay
  packages/react-components/src/components/ImageOverlay.tsx
  packages/react-composites/src/mocks/FakeChatAdapterArgs.ts
  packages/react-composites/tests/app/chat/FakeAdapterApp.tsx
  packages/react-composites/tests/app/images/inlineImageExample1-fullSize.png
  packages/react-composites/tests/browser/chat/hermetic/ImageOverlay.test.ts
  packages/react-composites/tests/browser/chat/hermetic/Messaging.test.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loaded-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-loading-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-broken-link-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-dark-mode-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ImageOverlay.test.ts-snapshots/image-overlay-modal-light-mode-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-broken-image-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loaded-stage-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/messaging-inline-image-loading-stage-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4574 [Chat] Wrap UI tests with themeProvider by default
  packages/react-components/playwright/index.tsx
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-insert-table-panel-selected-size-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-insert-table-panel-selected-size-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-insert-table-panel-selected-size-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-column-left-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-1-1-selection-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-1-1-selection-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-1-1-selection-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-4-3-selection-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-4-3-selection-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-4-3-selection-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-full-selection-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-full-selection-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInsertTablePane.spec.tsx-snapshots/rich-text-insert-table-pane-full-selection-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/TypingIndicator.spec.tsx-snapshots/typing-indicator-1-user-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/TypingIndicator.spec.tsx-snapshots/typing-indicator-1-user-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/TypingIndicator.spec.tsx-snapshots/typing-indicator-5-users-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/TypingIndicator.spec.tsx-snapshots/typing-indicator-5-users-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/TypingIndicator.spec.tsx-snapshots/typing-indicator-1-user-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/TypingIndicator.spec.tsx-snapshots/typing-indicator-1-user-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/TypingIndicator.spec.tsx-snapshots/typing-indicator-5-users-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/TypingIndicator.spec.tsx-snapshots/typing-indicator-5-users-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4497 Add confirmation that invite link has been copied
  change-beta/@azure-communication-react-f7b0edca-8ef1-4c0e-8e4b-7d1b57b28ea3.json
  change/@azure-communication-react-f7b0edca-8ef1-4c0e-8e4b-7d1b57b28ea3.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx
  packages/react-composites/src/composites/common/AddPeopleButton.tsx
  packages/react-composites/src/composites/common/AddPeopleDropdown.tsx
  packages/react-composites/src/composites/common/CalloutWithIcon.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#4577 [RTE] Copy paste plugin migration
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.test.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/KeyboardInputPlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/UpdateContentPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/styles/RichTextEditor.styles.ts
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
Labels: do not need changelog

#4581 Groom changelog
  packages/communication-react/CHANGELOG.stable.md
Labels: do not need changelog

#4556 [Chat]Add UI tests for inlineImage and ImageOverlay's loading stage and broken image stage
  packages/react-components/tests/browser/ImageOverlay.spec.tsx
  packages/react-components/tests/browser/MessageThread.spec.tsx
  packages/react-components/tests/snapshots/beta/ImageOverlay.spec.tsx-snapshots/image-overlay-loading-stage-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ImageOverlay.spec.tsx-snapshots/image-overlay-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ImageOverlay.spec.tsx-snapshots/image-overlay-loading-stage-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-broken-image-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-broken-image-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-broken-image-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-loading-stage-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-loading-stage-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/MessageThread.spec.tsx-snapshots/message-thread-inline-image-loading-stage-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4579 [Captions] captions adhoc
  change-beta/@azure-communication-react-b17887d7-fe19-4658-b57d-36fb6663620e.json
  change/@azure-communication-react-b17887d7-fe19-4658-b57d-36fb6663620e.json
  packages/calling-stateful-client/src/CallDeclarativeCommon.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.test.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts
Labels: breaking-change

#4583 Rich text toolbar migration
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/package.json
  packages/react-components/src/components/RichTextEditor/Buttons/RichTextRibbonButtons.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/RichTextToolbarPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/RichTextToolbar.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/Table/RichTextInsertTableButton.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/Table/RichTextInsertTablePane.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/Table/RichTextTableContextMenu.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/Table/insertTableAction.tsx
  packages/react-components/src/components/styles/RichTextEditor.styles.ts
  packages/react-components/src/components/utils/RichTextEditorStringsUtils.ts
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/tests/browser/TestingComponents/TestRichTextInsertTablePane.tsx
Labels: breaking-change, do not need changelog

#4457 Share localization string between sendbox and editbox
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils/RichTextEditorStringsUtils.ts
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: breaking-change

#4597 Use OIDC for azure blob uploads in release pipelines
  .github/workflows/alpha-release.yml
  .github/workflows/nightly-cd.yml
  .github/workflows/npm-release-publish.yml
  docs/releases/updating-npm-publishing-credentials.md
Labels: do not need changelog

#4594 [RTE] Context menu update
  packages/react-components/src/components/RichTextEditor/Plugins/ContextMenuPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
Labels: do not need changelog

#4599 Migrate touchdown build task to v4 using federated identity credentials
  .github/workflows/touchdown-pipeline/touchdown-build.yml
Labels: do not need changelog

#4607 [RTE] Enable skipped tests after the migration
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.test.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/Table/RichTextInsertTableCommandBarItem.tsx
  packages/react-components/tests/browser/ChatMessageComponentAsEditBox.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponent.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponentTablesTests.spec.tsx
  packages/react-components/tests/browser/RichTextInsertTablePane.spec.tsx
  packages/react-components/tests/browser/RichTextSendBox.spec.tsx
  packages/react-components/tests/browser/TestingComponents/TestRichTextInputBoxComponent.tsx
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-hover-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-1-text-format-at-a-time-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-1-text-format-at-a-time-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-1-text-format-at-a-time-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-all-text-formats-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-all-text-formats-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-all-text-formats-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-bulleted-list-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-bulleted-list-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-bulleted-list-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-numbered-list-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-numbered-list-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-text-formatted-numbered-list-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-with-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-with-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponent.spec.tsx-snapshots/rich-text-input-box-component-with-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-column-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-column-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-column-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-row-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-row-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-delete-row-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-column-left-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-column-left-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-column-left-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-above-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-above-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-above-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-below-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-below-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextInputBoxComponentTablesTests.spec.tsx-snapshots/rich-text-input-box-component-table-insert-additional-row-below-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-auto-focus-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-format-toolbar-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4617 Added strings for rich text editor
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#4619 Remove ppt live cc lines
  common/config/babel/features.js
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/PPTLiveSubscriber.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/RemoteScreenShare.tsx
  packages/react-components/src/components/VideoTile.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: do not need changelog

#4626 Update Strings in main for beta release(1.17.0-beta.1)
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: do not need changelog

#4627 Strings update for Message Thread and rich text editor feature
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: do not need changelog

#4598 Update breaking change check to checkout the SHA instead of the ref
  .github/workflows/breaking-change-check.yml
Labels: do not need changelog

#4645 Notification components
  change-beta/@azure-communication-react-01babd0e-72ed-4d48-ae90-6de6f3594b4f.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/NotificationBar.tsx
  packages/react-components/src/components/Notifications.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/NotificationBar.styles.ts
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook/stories/INTERNAL/NotificationBar/NotificationBar.stories.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/Notifications.stories.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotificationBar.snippet.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotifications.snippet.tsx
  packages/storybook/stories/controlsUtils.ts
Labels: breaking-change

#4530 [GA CTE] Add CTE to stable flag, adjustments for new stable sdk changes
  change-beta/@azure-communication-react-2d2cc7c8-c86e-4806-8e76-e09d7ea3e36f.json
  change-beta/@azure-communication-react-99ecec11-ac37-4a6d-a88f-dd7277ea21c0.json
  change/@azure-communication-react-2d2cc7c8-c86e-4806-8e76-e09d7ea3e36f.json
  change/@azure-communication-react-99ecec11-ac37-4a6d-a88f-dd7277ea21c0.json
  common/config/babel/features.js
  common/config/workflows/matrix.json
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/providers/CallAgentProvider.tsx
  packages/calling-component-bindings/src/providers/CallProvider.tsx
  packages/calling-stateful-client/src/TeamsCallDeclarative.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: breaking-change

#4661 End call screen for Call Failed due to bad request error (wrong ids, wrong links .etc)
  change-beta/@azure-communication-react-1069ab21-0cbc-42d4-98ca-163496f5780d.json
  change/@azure-communication-react-1069ab21-0cbc-42d4-98ca-163496f5780d.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallScreen.tsx
Labels: breaking-change, do not need changelog

#4666 Fix meta package symlinks
  packages/communication-react/scripts/verifyDependencies.js
  packages/communication-react/tsconfig.json
Labels: do not need changelog

#4576 Add meeting conference numbers info to stateful client
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#4673 Enable Avatar Hiding in MessageThread
  change-beta/@azure-communication-react-ca315b94-3fd4-4d6b-8dfe-24f17fa1b7a2.json
  change/@azure-communication-react-ca315b94-3fd4-4d6b-8dfe-24f17fa1b7a2.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ChatMessage/ChatMessageActionsFlyout.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/FluentChatMessageComponent.tsx
  packages/react-components/src/components/styles/MessageThread.styles.ts
  packages/react-components/src/types/OnRender.ts
Labels: breaking-change

#4678 Remove end call survey cc
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/communication-react/src/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/pages/SurveyPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/ThankYouForFeedbackPage.tsx
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/common/StarSurvey.tsx
  packages/react-composites/src/composites/common/Survey.tsx
  packages/react-composites/src/composites/common/SurveyContent.tsx
  packages/react-composites/src/composites/common/TagsSurvey.tsx
  packages/react-composites/src/composites/common/styles/Survey.styles.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/PageState.test.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/PageState.test.ts-snapshots/left-call-page-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4683 Soft mute participants
  change-beta/@azure-communication-react-7fac5799-c4eb-4b4a-a2b2-2927e765c3fb.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/hooks/usePropsFor.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/disabled-pin-menu-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGalleryLayout.test.ts-snapshots/video-tile-fit-to-frame-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGalleryLayout.test.ts-snapshots/video-tile-unpin-Desktop-Chrome-linux.png
Labels: breaking-change
