Repository Azure/communication-ui-library, pull requests merged in 2024-07, with the labels that each got.

#4793 [RTE] Fix content model reset for rich text send box
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
Labels: do not need changelog

#4802 update feature
  common/config/babel/features.js
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/MeetingConferencePhoneInfo.tsx
Labels: breaking-change

#4805 Move Soft mute to beta and address arb comment
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
Labels: breaking-change

#4815 Notifications now includes compliance banner
  change-beta/@azure-communication-react-6667f578-f8e6-426f-a384-65789f6e8070.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/HoldPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/TransferPage.tsx
  packages/react-composites/src/composites/CallComposite/utils/TrackErrors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
Labels: breaking-change

#4824 Update communication-calling to 1.26.1 and 1.27.1-beta.1
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change

#4814 [Chat] Image upload for RTE edit box
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
  packages/storybook8/stories/Components/SendBox/Docs.mdx
Labels: breaking-change, do not need changelog

#4758 Ruslanz/browser tests for conference info
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ErrorBar.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/NetworkReconnectTile.tsx
  packages/react-composites/src/composites/CallComposite/selectors/badNetworkQualitySelector.ts
  packages/react-composites/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-tile-when-ufd-network-reconnect-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
Labels: breaking-change

#4813 [RTE] Add tests for Rich Text Editor
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.test.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/TableEditContextMenuProvider.tsx
  packages/react-composites/src/composites/ChatComposite/ChatComposite.test.tsx
Labels: do not need changelog

#4833 Add text only mode support for Composites
  packages/chat-stateful-client/src/ChatClientState.ts
  packages/chat-stateful-client/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Labels: breaking-change, do not need changelog

#4829 [Incoming Call] Incoming call toast Notification
  change-beta/@azure-communication-react-18f931a8-6c2b-4c83-9636-bef036778ac7.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/IncomingCallNotification.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/storybook/stories/IncomingCallNotification/IncomingCallNotification.stories.tsx
  packages/storybook/stories/IncomingCallNotification/snippets/IncomingCallNotification.snippet.tsx
Labels: breaking-change

#4838 Change Close to Dismiss for button aria label
  change-beta/@azure-communication-react-58022293-11ec-42c3-9152-e3c9fe24d5c1.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/Notification.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook/stories/INTERNAL/NotificationBar/Notification.stories.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotification.snippet.tsx
Labels: breaking-change

#4823 [Chat] Handle image upload for RTE Edit Box resend
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/chat-component-bindings/src/utils/getImageAttachmentsFromHTMLContent.ts
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-composites/src/composites/ChatComposite/adapter/StubChatClient.ts
Labels: do not need changelog

#4839 [RTE] Add toggle for RichTextEditor to CallWithChat Sample
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  samples/CallWithChat/src/app/App.tsx
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/CallWithChat/src/app/views/RichTextEditorToggle.tsx
Labels: does not need changelog

#4841 [Incoming call] cc inbound icons
  change-beta/@azure-communication-react-8d3a5b27-5c04-4b00-8a98-e3ce437e0d1e.json
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/theming/icons.tsx
Labels: breaking-change

#4847 [Chat] Add image placeholder and broken image to my messages
  packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/styles/MessageThread.styles.ts
Labels: does not need changelog

#4826 [Chat]Disable image upload for Non Teams Interop Chats
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.test.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/UpdateContentPlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.test.ts
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/useImageUpload.tsx
Labels: does not need changelog

#4848 Text only mode tests for Composites
  packages/react-composites/src/composites/ChatComposite/ChatComposite.test.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Labels: does not need changelog

#4860 Stablize Notifications Feature
  change-beta/@azure-communication-react-f47dfffc-7d03-4552-8fe9-cc2932418f2d.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/Notification.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/failure-to-start-video-on-error-bar-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/failure-to-start-video-on-error-bar-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/failure-to-start-video-on-error-bar-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/multiple-errors-on-error-bar-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/multiple-errors-on-error-bar-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/multiple-errors-on-error-bar-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/one-error-dismissed-on-error-bar-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/one-error-dismissed-on-error-bar-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/ErrorBar.test.ts-snapshots/one-error-dismissed-on-error-bar-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-recovered-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-recovered-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-recovered-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-stops-unexpectedly-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-stops-unexpectedly-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-camera-stops-unexpectedly-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-recovered-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-recovered-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-recovered-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-when-camera-freezes-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-when-camera-freezes-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-when-camera-freezes-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-teams-meeting-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/tile-when-ufd-network-quality-is-bad-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-error-side-pane-closed-Desktop-Chrome-linux.png
  packages/storybook/stories/Notifications/Notification.stories.tsx
  packages/storybook/stories/Notifications/NotificationStack.stories.tsx
  packages/storybook/stories/Notifications/snippets/ExampleNotification.snippet.tsx
  packages/storybook/stories/Notifications/snippets/ExampleNotificationStack.snippet.tsx
  packages/storybook/stories/controlsUtils.ts
Labels: breaking-change

#4865 [Changelog] Groomed change log
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#4869 Fix lists tests for rich text editor
  packages/react-components/tests/browser/RichTextInputBoxComponent.spec.tsx
Labels: does not need changelog

#4867 review after arb
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/MeetingConferencePhoneInfo.test.tsx
  packages/react-components/src/components/MeetingConferencePhoneInfo.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/CallComposite/components/NetworkReconnectTile.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/useMeetingPhoneInfo.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/MeetingPhoneInfoPaneContent.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts
Labels: breaking-change

#4855 [Chat]Handle broken image for RTE editing
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/styles/Common.style.ts
  packages/react-components/src/components/styles/MessageThread.styles.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
Labels: does not need changelog

#4882 [RTE] Change msgPolicy to be an interface.
  packages/chat-stateful-client/src/ChatClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: does not need changelog

#4876 [RTE] Set image width height
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/styles/MessageThread.styles.ts
  packages/react-components/src/components/styles/RichTextEditor.styles.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
Labels: does not need changelog

#4879 Web UI library dependencies update
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-javascript-loaders/package.json
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-components/src/components/Attachment/AttachmentCard.tsx
  packages/react-components/src/components/styles/AttachmentCard.styles.ts
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-multiple-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-multiple-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-multiple-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-multiple-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-multiple-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-multiple-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-multiple-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-multiple-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-multiple-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-group-layout-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-group-layout-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-group-layout-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-singlular-layout-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-singlular-layout-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-progress-singlular-layout-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-group-layout-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-group-layout-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-group-layout-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-singular-layout-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-singular-layout-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachments-in-richtext-sendbox-with-progress-singular-layout-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-attachments-with-progress-Mobile-Android-Portrait-linux.png
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog

#4885 SettingUpReactHooks storybook page update
  packages/storybook/stories/Stateful Client/SettingUpReactHooks.stories.mdx
Labels: does not need changelog

#4863 Point npm releases to new ADO release pipeline
  .github/workflows/alpha-release.yml
  .github/workflows/nightly-cd.yml
  .github/workflows/npm-release-publish.yml
  common/scripts/poll-npm-package-published.mjs
Labels: does not need changelog

#4881 Fix mic button cropped offscreen at 400% zoom
  samples/Calling/src/app/App.tsx
  samples/Calling/src/app/views/CallCompositeContainer.tsx
  samples/Calling/src/index.css
  samples/Calling/src/index.tsx
Labels: does not need changelog

#4874 RoosterJS dependencies update
  change-beta/@azure-communication-react-f395dd7f-5c1d-4c04-96a5-2560d0cac3c2.json
  change/@azure-communication-react-f395dd7f-5c1d-4c04-96a5-2560d0cac3c2.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/package.json
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/RichTextToolbar.tsx
  packages/react-components/src/components/utils/RichTextEditorUtils.ts
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
  packages/storybook8/stories/Composites/ChatComposite/Docs.mdx
Labels: breaking-change

#4880 [End Call For Everyone] Add storybook info on end call for everyone and disabling modal
  packages/storybook/stories/CallComposite/CallCompositeDocs.tsx
  packages/storybook8/stories/Composites/CallComposite/Docs.mdx
Labels: does not need changelog

#4864 [Inbound Outbound typing] cte incoming updates
  change-beta/@azure-communication-react-543adcf2-89fa-4813-9284-7ba5acbbdfcc.json
  change-beta/@azure-communication-react-5f2d1ffe-f3ca-4d44-99d0-657d1bbe5783.json
  packages/calling-stateful-client/src/CallAgentDeclarative.ts
  packages/calling-stateful-client/src/CallAgentDeclarativeCommon.ts
  packages/calling-stateful-client/src/IncomingCallDeclarative.ts
  packages/calling-stateful-client/src/TeamsCallAgentDeclarative.ts
  packages/calling-stateful-client/src/TeamsIncomingCallDeclarative.ts
  packages/calling-stateful-client/src/TypeGuards.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#4892 Fix images added in Edit box not send out correctly
  packages/react-components/src/components/utils/SendBoxUtils.ts
Labels: does not need changelog

#4870 [Chat] Handle multiple messages editing with inline images
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadReducer.ts
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/useImageUpload.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
  packages/react-composites/src/composites/common/constants.ts
Labels: breaking-change, does not need changelog

#4888 Web UI library dependencies update
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-javascript-loaders/package.json
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog

#4896 [Chat] Fix broken image size in the RTE Edit box after the image size changes
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
Labels: does not need changelog

#4904 [RTE] CC Fix
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
Labels: does not need changelog

#4897 fixing tables and adding in identity concepts page
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/storybook8/.storybook/main.ts
  packages/storybook8/package.json
  packages/storybook8/stories/Concepts/Identity/Docs.mdx
  packages/storybook8/stories/Overview.mdx
  packages/storybook8/stories/StatefulClient/Chat/Chat.mdx
Labels: documentation, does not need changelog

#4912 [Storybook8] Migrate Stateful Client stories to V8
  packages/storybook8/stories/StatefulClient/Call/Docs.mdx
  packages/storybook8/stories/StatefulClient/Call/snippets/CallAppStateful.snippet.tsx
  packages/storybook8/stories/StatefulClient/Call/snippets/CallAppStatefulComplete.snippet.tsx
  packages/storybook8/stories/StatefulClient/Call/snippets/CallAppStatefulProviders.snippet.tsx
  packages/storybook8/stories/StatefulClient/Call/snippets/CallComponentsStateful.tsx
  packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
  packages/storybook8/stories/StatefulClient/Overview.mdx
Labels: documentation, does not need changelog

#4908 [RTE] Storybook update
  packages/storybook/stories/CallWithChatComposite/CallWithChatCompositeDocs.tsx
  packages/storybook/stories/ChatComposite/ChatCompositeDocs.tsx
  packages/storybook/stories/ChatComposite/snippets/RichTextEditor.snippet.tsx
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook/stories/MessageThread/snippets/WithRichTextEditorOnPasteCallback.snippet.tsx
  packages/storybook/stories/SendBox/RichTextSendBox.stories.tsx
  packages/storybook/stories/SendBox/snippets/RichTextSendBoxOnPasteCallback.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/Docs.mdx
  packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
  packages/storybook8/stories/Components/MessageThread/index.stories.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditor.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditorOnPaste.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/placeholdermessages.ts
  packages/storybook8/stories/Composites/ChatComposite/Docs.mdx
  packages/storybook8/stories/Composites/ChatComposite/snippets/RichTextEditor.snippet.tsx
  packages/storybook8/stories/controlsUtils.ts
Labels: does not need changelog

#4905 [Storybook 8] add accessibility page to sb 8
  packages/storybook8/stories/Concepts/Accesibility/Docs.mdx
Labels: documentation, does not need changelog

#4903 [storybook 8] Add callingsounds concept to 8
  packages/storybook8/stories/Concepts/AddingSounds/Docs.mdx
  packages/storybook8/stories/Concepts/AddingSounds/snippets/CallingSoundsSnippet.snippet.tsx
Labels: documentation, does not need changelog

#4923 [Storybook 8] add PPTLive SB page
  packages/storybook8/public/images/pptlive-example.png
  packages/storybook8/stories/Concepts/PowerPointLive/Doc.mdx
  packages/storybook8/stories/Concepts/PowerPointLive/snippets/PPTLive.snippet.tsx
Labels: documentation, does not need changelog

#4928 Added richTextBulletedListAppliedAnnouncement and richTextNumberedListAppliedAnnouncement to message thread strings
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: does not need changelog

#4919 [Chat] Add different error bar type for SendBoxErrorBar and add localization
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.tsx
  packages/react-components/src/components/SendBoxErrorBar.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-richtext-sendbox-with-error-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-richtext-sendbox-with-error-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-richtext-sendbox-with-error-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-error-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-error-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-sendbox-with-error-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-and-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMessageComponentAsEditBox.spec.tsx-snapshots/chat-message-component-as-rich-text-edit-box-with-system-error-without-format-toolbar-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/RichTextSendBox.spec.tsx-snapshots/rich-text-send-box-with-system-message-Mobile-Android-Portrait-linux.png
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/ChatComposite/Strings.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  samples/Chat/src/app/utils/uploadHandler.ts
Labels: breaking-change, does not need changelog

#4927 Storybook update with rich text editor changes
  packages/storybook/stories/CallWithChatComposite/BasicExample.stories.tsx
  packages/storybook/stories/CallWithChatComposite/JoinExample.stories.tsx
  packages/storybook/stories/ChatComposite/RichTextEditor.stories.tsx
  packages/storybook/stories/ChatComposite/snippets/Container.snippet.tsx
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook8/stories/Components/MessageThread/Docs.mdx
  packages/storybook8/stories/Composites/ChatComposite/RichTetEditorExample.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/snippets/Container.snippet.tsx
Labels: does not need changelog

#4898 adding in cte page and changing what goes into the nav pane
  packages/storybook8/.storybook/preview.tsx
  packages/storybook8/stories/Concepts/CommunicationAsTeamsUser/Docs.mdx
  packages/storybook8/stories/Concepts/CommunicationAsTeamsUser/snippets/CommunicationAsTeamsUser.snippet.tsx
Labels: documentation, does not need changelog

#4949 Fix Jest Text Failure in PRs
  packages/calling-stateful-client/src/DeviceManager.test.ts
Labels: breaking-change, does not need changelog

#4884 [Inbound Calling] Add component binding for IncomingCallNotication
  change-beta/@azure-communication-react-73cd2f79-efd7-4652-be4f-ea890a54834a.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/incomingCallStackSelector.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/utils/callUtils.ts
  packages/calling-stateful-client/src/BetaToStableTypes.ts
  packages/calling-stateful-client/src/CallAgentDeclarativeCommon.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/IncomingCallSubscriber.ts
  packages/calling-stateful-client/src/TypeGuards.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/calling-stateful-client/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/IncomingCallStack.tsx
  packages/react-components/src/components/index.ts
  samples/CallingStateful/src/App.tsx
  samples/CallingStateful/src/views/CallScreen.tsx
  samples/CallingStateful/src/views/Homescreen.tsx
Labels: breaking-change

#4942 [Chat]Rename Image upload APIs and disable image pasting when onInsertInlineImage callback is not provided
  packages/acs-ui-common/src/index.ts
  packages/acs-ui-common/src/removeImageTags.test.ts
  packages/acs-ui-common/src/removeImageTags.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-composites/src/composites/ChatComposite/ChatComposite.test.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
Labels: breaking-change, does not need changelog

#4948 Storybook Migration Video Effects
  packages/storybook8/stories/Concepts/VideoEffects/Doc.mdx
  packages/storybook8/stories/Concepts/VideoEffects/snippets/VideoEffectsSnippet.snippet.tsx
Labels: does not need changelog

#4952 [Incoming Calls] accept options with video drop down
  packages/calling-component-bindings/src/incomingCallStackSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/IncomingCallNotification.tsx
  packages/react-components/src/components/IncomingCallStack.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook/stories/INTERNAL/IncomingCallNotification/IncomingCallNotification.stories.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/snippets/IncomingCallNotification.snippet.tsx
  packages/storybook/stories/INTERNAL/IncomingCallNotification/snippets/IncomingCallNotificationStyling.snippet.tsx
  samples/CallingStateful/src/components/IncomingCallManager.tsx
Labels: breaking-change

#4917 [Storybook8] Migrate React hooks and best practices to V8
  packages/storybook8/stories/StatefulClient/BestPractices.mdx
  packages/storybook8/stories/StatefulClient/ReactHooks/SettingUpReactHooks.mdx
  packages/storybook8/stories/StatefulClient/ReactHooks/UsePropsForHook.mdx
  packages/storybook8/stories/StatefulClient/ReactHooks/UseSelector.mdx
Labels: documentation, does not need changelog

#4946 Storybook 8 Migration Reactions
  packages/storybook8/stories/Concepts/MeetingReactions/Doc.mdx
  packages/storybook8/stories/Concepts/MeetingReactions/snippets/MeetingReactionsSnippet.snippet.tsx
Labels: does not need changelog

#4944 Survey migration for Storybook 8
  packages/storybook8/stories/Concepts/Survey/Doc.mdx
  packages/storybook8/stories/Concepts/Survey/Survey.story.tsx
  packages/storybook8/stories/Concepts/Survey/index.stories.tsx
  packages/storybook8/stories/Concepts/Survey/utils/SurveyDocs.tsx
  packages/storybook8/stories/Concepts/Survey/utils/SurveyExample.tsx
Labels: does not need changelog

#4959 Temporarily skip failing test due to infra to get CI green
  samples/tests/ComponentExamples/ComponentExamples.test.ts
Labels: does not need changelog

#4924 Storybook 8 migration for notification and notification stack component
  packages/storybook8/stories/Components/Notification/Doc.mdx
  packages/storybook8/stories/Components/Notification/Notification.story.tsx
  packages/storybook8/stories/Components/Notification/index.stories.tsx
  packages/storybook8/stories/Components/Notification/snippets/Notification.snippet.tsx
  packages/storybook8/stories/Components/NotificationStack/Doc.mdx
  packages/storybook8/stories/Components/NotificationStack/NotificationStack.story.tsx
  packages/storybook8/stories/Components/NotificationStack/index.stories.tsx
  packages/storybook8/stories/Components/NotificationStack/snippets/NotificationStack.snippet.tsx
  packages/storybook8/stories/controlsUtils.ts
Labels: does not need changelog

#4955 [Chat] Add RTE Image upload to storybook components and composites
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/storybook/stories/ChatComposite/ChatCompositeDocs.tsx
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook/stories/MessageThread/snippets/WithRichTextEditorInlineImages.snippet.tsx
  packages/storybook/stories/SendBox/RichTextSendBox.stories.tsx
  packages/storybook/stories/SendBox/snippets/RichTextSendBoxWithInlineImages.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/Docs.mdx
  packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
  packages/storybook8/stories/Components/MessageThread/index.stories.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditorInlineImages.snippet.tsx
  packages/storybook8/stories/Composites/ChatComposite/Docs.mdx
Labels: does not need changelog

#4972 Revert "Dependency minor updates"
  change-beta/@azure-communication-react-de7afe3c-8419-4aff-aa60-c951d258c275.json
  change/@azure-communication-react-de7afe3c-8419-4aff-aa60-c951d258c275.json
  common/config/jest/jest.config.js
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/jest.config.js
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/jest.config.js
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  packages/storybook8/stories/Feedback.mdx
  packages/storybook8/stories/Overview.mdx
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#4956 Add breakout rooms to stateful layer and exposed events to adapters
  change-beta/@azure-communication-react-5762e573-181a-45bd-8ef5-8a73dd28ec27.json
  change/@azure-communication-react-5762e573-181a-45bd-8ef5-8a73dd28ec27.json
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
Labels: breaking-change

#4967 [Storybook 8] Concepts/Capabilities Page
  packages/storybook8/stories/Concepts/Capabilities/Docs.mdx
  packages/storybook8/stories/Concepts/Capabilities/snippets/CapabilitiesChangedListener.snippet.tsx
Labels: does not need changelog

#4966 [Storybook 8] Concepts/Transfer Page
  packages/storybook8/stories/Concepts/Transfer/Docs.mdx
  packages/storybook8/stories/Concepts/Transfer/snippets/Transfer.snippet.tsx
Labels: does not need changelog

#4970 [Storybook 8] Composites/Adapters
  packages/storybook8/.storybook/main.ts
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
  packages/storybook8/stories/Composites/Adapters/snippets/CallAdapterExample.snippet.tsx
  packages/storybook8/stories/Composites/Adapters/snippets/CallAdapterStateChanges.snippet.txt
  packages/storybook8/stories/Composites/Adapters/snippets/ChatAdapterExample.snippet.tsx
  packages/storybook8/stories/Composites/Adapters/snippets/ChatAdapterStateChanges.snippet.txt
  packages/storybook8/stories/utils/Note.tsx
Labels: does not need changelog

#4921 [Localization] Updated to latest localization strings
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#4963 [Inbound Calling] Calling stateful sample fixes
  samples/CallingStateful/src/App.tsx
  samples/CallingStateful/src/components/CallManager.tsx
  samples/CallingStateful/src/views/CallScreen.tsx
  samples/CallingStateful/src/views/Homescreen.tsx
  samples/CallingStateful/src/views/Login.tsx
Labels: does not need changelog

#4968 [Storybook 8] Concepts/Spotlight Page
  packages/storybook8/stories/Concepts/Spotlight/Docs.mdx
  packages/storybook8/stories/Concepts/Spotlight/snippets/CustomSpotlightComponents.snippet.tsx
  packages/storybook8/stories/Concepts/Spotlight/snippets/CustomSpotlightComposite.snippet.tsx
  packages/storybook8/stories/Concepts/Spotlight/snippets/HideSpotlight.snippet.tsx
  packages/storybook8/stories/Concepts/Spotlight/snippets/SpotlightEvent.snippet.tsx
Labels: does not need changelog

#4969 [Storybook 8] Concepts/HideAttendeeNames Page
  packages/storybook8/public/images/hideAttendee-Attendeeview.png
  packages/storybook8/public/images/hideAttendees-PresenterView.png
  packages/storybook8/stories/Concepts/HideAttendeeNames/Docs.mdx
Labels: does not need changelog

#4971 [Storybook 8] Composites/CrossFrameworkSupport Page
  packages/storybook8/stories/Composites/CrossFrameworkSupport/Docs.mdx
Labels: does not need changelog

#4976 [Storybook 8] Components/Error Bar
  packages/storybook8/stories/Components/ErrorBar/Docs.mdx
  packages/storybook8/stories/Components/ErrorBar/ErrorBar.story.tsx
  packages/storybook8/stories/Components/ErrorBar/index.stories.tsx
  packages/storybook8/stories/Components/ErrorBar/snippets/ExampleErrorBar.snippet.tsx
Labels: does not need changelog

#4978 Alkwa/upgrade storybook to 8.2.6
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/storybook8/package.json
Labels: does not need changelog

#4975 [Storybook 8] Components/Unsupported Browser
  packages/storybook8/stories/Components/SitePermissions/Docs.mdx
  packages/storybook8/stories/Components/UnsupportedBrowser/Docs.mdx
  packages/storybook8/stories/Components/UnsupportedBrowser/UnsupportedBrowser.story.tsx
  packages/storybook8/stories/Components/UnsupportedBrowser/index.stories.tsx
  packages/storybook8/stories/Components/UnsupportedBrowser/snippets/UnsupportedBrowserExamples.snippet.tsx
  packages/storybook8/stories/Components/UnsupportedBrowser/snippets/UnsupportedEnvironmentModal.snippet.tsx
Labels: does not need changelog

#4836 Update Rooms and Spotlight storybook page
  packages/storybook/stories/Adapters/Adapters.stories.mdx
  packages/storybook/stories/Rooms.stories.mdx
  packages/storybook/stories/Spotlight.stories.mdx
Labels: does not need changelog

#4965 Transition to breakout room on join event and go back to main meeting when room closes
  change-beta/@azure-communication-react-0f4d2b79-2d35-4625-a7f7-5025f6e4fe53.json
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
Labels: breaking-change

#4980 [RTE] Resolve issue where attachments were lost when editing a message
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Labels: does not need changelog
