Repository Azure/communication-ui-library, pull requests merged in 2024-10, with the labels that each got.

#5227 Changelog script fix
  common/scripts/changelog/check.mjs
  common/scripts/changelog/utils.mjs
Labels: does not need changelog

#5230 Create groom me file for groom changelog branch
  packages/communication-react/CHANGELOG.beta.md
Labels: does not need changelog

#5232 Dmceachernmsft/release UI 1.20.0 beta.1
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-disabled-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Reactions.test.ts-snapshots/reaction-sub-menu-in-ongoing-call-in-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Reactions.test.ts-snapshots/reaction-sub-menu-in-ongoing-call-in-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-disabled-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/default-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/speaker-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-microphone-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-microphone-screen-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-speaker-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-speaker-screen-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-screen-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5152 Together mode client state and subscriber implementation
  change-beta/@azure-communication-react-367d1747-182e-425c-a897-cbcdfbc06ecd.json
  change-beta/@azure-communication-react-43b808a4-0c26-4119-a26b-7d31efbb2b93.json
  change-beta/@azure-communication-react-839f12bb-f1d6-43dc-9ba8-41fc6b17baaf.json
  change-beta/@azure-communication-react-a9fb84d9-5a0a-43a1-b407-decf5c80312c.json
  change-beta/@azure-communication-react-c5b508a6-370f-414d-9663-905d1ef3f69b.json
  change-beta/@azure-communication-react-ebad70bc-6036-4b67-b5f9-438a20702e0e.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/StreamUtils.ts
  packages/calling-stateful-client/src/TogetherModeSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: breaking-change, does not need changelog

#5237 [bugfix][storybookv8] Use image of local screenshare for Videogallery screenshare presenter view
  packages/storybook8/public/images/video-gallery-screensharing-from-presenter.png
  packages/storybook8/stories/Components/VideoGallery/index.stories.tsx
  packages/storybook8/stories/Components/VideoGallery/snippets/VideoGalleryImages.tsx
Labels: does not need changelog

#5245 [Cherry-pick] Add Welsh strings (#5243)
  change-beta/@azure-communication-react-cb854d3f-732e-4c9a-8156-dc31df49ad74.json
  change/@azure-communication-react-cb854d3f-732e-4c9a-8156-dc31df49ad74.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/localization/locales/cy-GB/ComponentLocale.tsx
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/index.ts
  packages/react-composites/src/composites/localization/locales/cy-GB/CompositeLocale.tsx
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
Labels: does not need changelog

#5247 fix sb issue inbound calling
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/Docs.mdx
Labels: does not need changelog

#5249 [Inbound Calling] SB Page fix in v8
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/Docs.mdx
Labels: does not need changelog

#5250 [JS-loaders] fix composite options spread
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Labels: does not need changelog

#5251 [Cherry-pick] js loaders fix
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Labels: does not need changelog

#5255 Add more robust checks to composite javascript tests to fix flakey tests
  samples/tests/StaticHtmlComposites/CompositeJavascriptTest.test.ts
Labels: does not need changelog

#5234 Update webpack version and postcss to latest for fixing dependabot alerts
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
Labels: does not need changelog

#5254 [SB8] inbound calling fix page Meta import and links
  packages/storybook8/stories/Concepts/InboundCalling/Docs.mdx
Labels: does not need changelog

#5248 Add Welsh to storybook
  packages/react-components/src/components/VideoGallery.test.tsx
  packages/storybook/stories/Localization.stories.mdx
  packages/storybook/stories/locales.ts
  packages/storybook8/stories/Concepts/Localization/Docs.mdx
  packages/storybook8/stories/locales.ts
Labels: does not need changelog

#5257 [SB8] inbound calling fix page Meta import and links (#5254)
  packages/storybook8/stories/Concepts/InboundCalling/Docs.mdx
Labels: does not need changelog

#5235 Update from cpx to cpy (dependabot fixes)
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-composites/package.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog

#5258 [SDK] update calling SDK
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5236 Add eslint rule to guard against improper usage of `adapter.getState()`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-composites/.eslintrc.js
  packages/react-composites/package.json
  rush.json
  tools/custom-eslint-rules/index.js
  tools/custom-eslint-rules/package.json
  tools/custom-eslint-rules/readme.md
  tools/custom-eslint-rules/rules/no-getstate.js
Labels: does not need changelog

#5196 Add aria label for video effects pane
  change-beta/@azure-communication-react-361438b2-fe57-42c6-979e-621cddbf7602.json
  change/@azure-communication-react-361438b2-fe57-42c6-979e-621cddbf7602.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/SidePane.tsx
  packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#5262 Enable rich editor by default in samples
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/Chat/src/app/App.tsx
Labels: does not need changelog

#5263 [Cherry-pick] Add Welsh to storybook (#5248)
  packages/react-components/src/components/VideoGallery.test.tsx
  packages/storybook/stories/Localization.stories.mdx
  packages/storybook/stories/locales.ts
  packages/storybook8/stories/Concepts/Localization/Docs.mdx
  packages/storybook8/stories/locales.ts
Labels: does not need changelog

#5261 Fix deploy command for storybook 8 prod deploy
  .github/workflows/deploy-storybook.yml
Labels: does not need changelog

#5264 [Calling Stateful] README updates
  samples/CallingStateful/Media/homescreen.png
  samples/CallingStateful/Media/loginscreen.png
  samples/CallingStateful/README.md
Labels: does not need changelog

#5272 Add missing permission to deploy storybook
  .github/workflows/deploy-storybook.yml
Labels: does not need changelog

#5212 [ReadMe] Fix links to pages for storybook8
  docs/architecture/Overview.md
Labels: does not need changelog

#5273 Update storybook deploy permission
  .github/workflows/deploy-storybook.yml
Labels: does not need changelog

#5278 [ReadMe] Fixing readme storybook links
  README.md
  packages/communication-react/README.md
Labels: does not need changelog

#5246 Remove cc tags for acs captions
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallDeclarativeCommon.ts
  packages/calling-stateful-client/src/CaptionsSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
  packages/react-composites/tests/browser/call/hermetic/ClosedCaptions.test.ts
  packages/react-composites/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts
  packages/react-composites/tests/browser/common/constants.ts
Labels: does not need changelog

#5267 Detect local version of typescript in vscode
  .vscode/settings.json
Labels: does not need changelog

#5202 [JS-loaders] Conceptual docs
  packages/storybook8/stories/Composites/JavaScriptBundle/Docs.mdx
  packages/storybook8/stories/Composites/TypeScriptLoading/Docs.mdx
Labels: does not need changelog

#5285 Dependency updates
  common/autoinstallers/rush-cpy/package.json
  common/autoinstallers/rush-cpy/pnpm-lock.yaml
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5290 [A11y bugfix] update to announce menu state in participant item
  packages/react-components/src/components/ParticipantItem.tsx
Labels: does not need changelog

#5291 Set RTE toggle visual state to default to checked.
  samples/CallWithChat/src/app/views/RichTextEditorToggle.tsx
  samples/Chat/src/app/RichTextEditorToggle.tsx
Labels: does not need changelog

#5265 [DNS] stabilize feature
  change-beta/@azure-communication-react-95db09fa-bca5-48f4-b7be-bf7cd4a97ed2.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/MicrophoneButton.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.ts
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependencyLazy.ts
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
Labels: breaking-change, does not need changelog

#5292 Fix dependabot/249 - `cookie` npm package needs >= 0.7.0
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/Server/package.json
  samples/Server/src/app.ts
  samples/tests/package.json
Labels: does not need changelog

#5288 [A11y bugfix] fix aria behavior for local tile is not movable
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/FloatingLocalVideo.tsx
Labels: does not need changelog

#5296 [Deps] Remove unused http dependency
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  samples/StaticHtmlComposites/package.json
Labels: does not need changelog

#5289 Fix random eslint errors
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/prepare-package-json.js
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5298 [Storybook] BugFix to fill in the sendMessage method signature
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
Labels: does not need changelog

#5302 Remove stale ref to http in stable lock
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
Labels: does not need changelog

#5301 Revert "Fix random eslint errors "
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/prepare-package-json.js
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5304 [JS-loaders] js loader arb comments
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Labels: does not need changelog

#5287 [VideoGallery] fix logic for state strings
  packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.ts
  packages/react-composites/tests/browser/call/hermetic/OverflowGallery.test.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/scrollable-horizontal-gallery-with-joining-participant-dragged-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-2-joining-participants-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-in-grid-and-overflow-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Desktop-Chrome-16-9-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/overflow-gallery-with-joining-participant-with-multi-page-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/OverflowGallery.test.ts-snapshots/scrollable-horizontal-gallery-with-joining-participant-dragged-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5305 Downgrade Prettier to 5.1.3 for ESlint issue
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5300 Enable reactions button render for teams user in meeting scenario
  samples/Calling/src/app/views/CallScreen.tsx
Labels: does not need changelog

#5306 update basic build command to use generate module and sub
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
Labels: does not need changelog

#5314 Update string translation actions, remove PAT token usage
  .github/workflows/run-td-build.yml
  .github/workflows/touchdown-pipeline/touchdown-build.yml
  docs/references/string-translations.md
Labels: does not need changelog

#5315 Fix rush changelog; update changefile detection regex and add unit tests
  .github/workflows/ci.yml
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/changelog/utils.mjs
  common/scripts/changelog/utils.test.js
  common/scripts/jest.config.js
  common/scripts/package.json
  common/scripts/scripts-tests-setup/babel-config-jest.js
Labels: does not need changelog

#5317 1.20.0 changelog
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#5283 Fix issue where devices where not queried after permissions are changed in the browser
  change/@azure-communication-react-6e213483-fefe-4289-9b60-417e8476d863.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/CallComposite.test.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallReadinessModal.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
Labels: breaking-change

#5320 update calling-effects to be right peer-dep
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/force-build-flavor.mjs
  packages/calling-component-bindings/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
Labels: does not need changelog

#5324 Cherry-pick string updates to release 1.20.0
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5326 [JS-loaders] update API per ARB (#5322)
  change-beta/@azure-communication-react-9027708a-39a4-4de9-bc14-a6f55681f927.json
  change/@azure-communication-react-9027708a-39a4-4de9-bc14-a6f55681f927.json
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
Labels: breaking-change

#5327 Cherrypick communication effects updates (#5320) to release/1.20.0
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/force-build-flavor.mjs
  packages/calling-component-bindings/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
Labels: does not need changelog

#5328 Make environmentInfo stable - fixes safari speaker issue in stable
  change-beta/@azure-communication-react-601fa9cc-a5ef-444f-ba11-fcfbce7c9a70.json
  change-beta/@azure-communication-react-deda54f5-fac2-4f69-82ac-ac90b00c63f7.json
  change/@azure-communication-react-601fa9cc-a5ef-444f-ba11-fcfbce7c9a70.json
  change/@azure-communication-react-deda54f5-fac2-4f69-82ac-ac90b00c63f7.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/utils/callUtils.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
Labels: breaking-change

#5332 Cherry-pick #5328 to 1.20.0
  change-beta/@azure-communication-react-601fa9cc-a5ef-444f-ba11-fcfbce7c9a70.json
  change-beta/@azure-communication-react-deda54f5-fac2-4f69-82ac-ac90b00c63f7.json
  change/@azure-communication-react-601fa9cc-a5ef-444f-ba11-fcfbce7c9a70.json
  change/@azure-communication-react-deda54f5-fac2-4f69-82ac-ac90b00c63f7.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/utils/callUtils.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
Labels: breaking-change

#5308 Remove "teams-identity-support" conditional-compile code
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createDefaultCallingHandlersForComponent.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/providers/CallAgentProvider.tsx
  packages/calling-component-bindings/src/providers/CallProvider.tsx
  packages/calling-stateful-client/src/BetaToStableTypes.ts
  packages/calling-stateful-client/src/CallAgentDeclarativeCommon.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/TeamsCallAgentDeclarative.ts
  packages/calling-stateful-client/src/TeamsCallDeclarative.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/calling-stateful-client/src/TypeGuards.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/CallComposite/adapter/createHandlers.ts
  packages/react-composites/src/composites/CallComposite/adapter/index.ts
  packages/react-composites/src/composites/CallComposite/index.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  samples/Calling/src/app/App.tsx
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: breaking-change, does not need changelog

#5334 Merge `Prerelease/1.20.0` to main
  change/@azure-communication-react-1613cd0b-4030-4c16-a819-73169c2cae7f.json
  change/@azure-communication-react-2370b346-59bb-4073-9237-5f3206c9dbc0.json
  change/@azure-communication-react-3609656d-b6a9-4253-93ee-50eacf1719e2.json
  change/@azure-communication-react-361438b2-fe57-42c6-979e-621cddbf7602.json
  change/@azure-communication-react-4a7eb3ab-7f30-4012-9a9a-d8813f2deaf0.json
  change/@azure-communication-react-527f3dcc-8529-4085-9f64-ab4825026cc9.json
  change/@azure-communication-react-53fb5e2d-7cd9-4787-a9e2-8111a2247bbd.json
  change/@azure-communication-react-5c97ff3e-4d23-4829-82ed-3e7e068595f4.json
  change/@azure-communication-react-7910162a-6305-40a6-9763-756dc4f65c61.json
  change/@azure-communication-react-8dad3734-cbd4-42d3-ae33-07faa73a4923.json
  change/@azure-communication-react-937f9a6e-0f05-443a-a7c2-e6330fd6b9af.json
  change/@azure-communication-react-95728593-daf7-44cf-b16c-ad70f53c9083.json
  change/@azure-communication-react-99e73a18-df91-4d0d-9718-fb1302d34686.json
  change/@azure-communication-react-a33f45ab-78c2-4cc2-bc1d-426376fad0cc.json
  change/@azure-communication-react-a55926bb-4313-4043-b9a7-1802111c6192.json
  change/@azure-communication-react-b7391df0-c3f4-490f-84ad-b97252d3a49d.json
  change/@azure-communication-react-cb854d3f-732e-4c9a-8156-dc31df49ad74.json
  change/@azure-communication-react-da34ff2d-0333-491a-91e0-7bc44b7eb627.json
  change/@azure-communication-react-dd7317f8-5a22-4eb5-accb-0f9de6a60bc2.json
  change/@azure-communication-react-fb94b281-44f7-49f9-b8dd-42188767be50.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.json
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
  tools/custom-eslint-rules/package.json
Labels: does not need changelog

#5307 removing end-call-options cc flags
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/EndCallButton.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallCompositeContainer.tsx
Labels: breaking-change, does not need changelog

#5335 [BugFix a11y] a11y reader fixes
  packages/react-components/src/components/MeetingConferencePhoneInfo.tsx
  packages/react-components/src/components/VerticalGallery.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: does not need changelog

#5341 Remove conditional-compile lines for DNS
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/src/index.ts
  packages/react-components/src/components/MicrophoneButton.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/createHandlers.ts
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/CallComposite/components/buttons/Microphone.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.ts
  packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependencyLazy.ts
  packages/react-composites/src/composites/index.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallScreen.tsx
Labels: does not need changelog

#5342 remove conditional-compile lines for soft mute
  common/config/babel/features.js
  packages/calling-component-bindings/src/errorBarSelector.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/ErrorBar.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/PeoplePane.test.ts
  packages/react-composites/tests/browser/call/hermetic/RoomsCallScreen.test.ts
  packages/react-composites/tests/browser/call/hermetic/VideoGallery.test.ts
Labels: does not need changelog

#5340 remove conditional-compile lines for composite-js-helpers
  common/config/babel/features.js
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
  packages/communication-react/src/api-summary.ts
  packages/communication-react/src/javascript-loaders.ts
Labels: does not need changelog

#5339 remove `notifications` from features.js
  common/config/babel/features.js
Labels: does not need changelog

#5344 Add rush update:beta
  common/config/rush/command-line.json
  docs/contributing-guide/1. getting-set-up.md
  docs/contributing-guide/6. submitting-a-pr.md
  docs/infrastructure/rush.md
  packages/react-composites/tests/README.md
  samples/StaticHtmlComposites/README.md
Labels: does not need changelog

#5343 Remove conditional-compile lines for file-sharing-teams-interop
  common/config/babel/features.js
  packages/acs-ui-common/src/common.ts
  packages/chat-component-bindings/src/messageThreadSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/Attachment/AttachmentDownloadCards.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/FluentChatMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/utils/ChatMessageComponentUtils.tsx
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/ChatMessage.ts
Labels: does not need changelog

#5350 [Storybook] Removed an extra internal folder under components directory
  packages/storybook8/stories/Components/INTERNAL/CaptionsBanner/CaptionsBanner.tsx
  packages/storybook8/stories/Components/INTERNAL/CaptionsBanner/index.stories.tsx
  packages/storybook8/stories/Components/INTERNAL/CaptionsBanner/mockCaptions.ts
Labels: does not need changelog

#5345 [BugFix A11y] video tile a11y updates
  change-beta/@azure-communication-react-801d4bf5-46a3-4198-9dd6-6724c7eff2c3.json
  change/@azure-communication-react-801d4bf5-46a3-4198-9dd6-6724c7eff2c3.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5321 Fix final noUncheckedIndexedAccess in samples and tooling
  packages/communication-react/tsconfig.json
  packages/communication-react/tsconfig.preprocess.json
  packages/fake-backends/src/FakeChatThreadClient.ts
  packages/fake-backends/src/Model.ts
  packages/fake-backends/src/ThreadEventEmitter.ts
  packages/fake-backends/src/utils.ts
  packages/fake-backends/tsconfig.json
  packages/fake-backends/tsconfig.preprocess.json
  packages/storybook8/stories/Components/ControlBar/Buttons/Devices/snippets/DevicesButtonWithKnobs.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/MessageWithCustomMentionRenderer.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditor.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditorInlineImages.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/WithRichTextEditorOnPaste.snippet.tsx
  packages/storybook8/stories/Components/SendBox/RichTextSendBox/RichTextSendBox.story.tsx
  packages/storybook8/stories/Components/SendBox/RichTextSendBox/snippets/RichTextSendBoxWithInlineImages.snippet.tsx
  packages/storybook8/stories/Components/VideoTile/snippets/StylingVideoTile.snippet.tsx
  packages/storybook8/stories/Composites/ChatComposite/snippets/Utils.tsx
  packages/storybook8/stories/Concepts/Styling/snippets/StylingVideoTile.snippet.tsx
  packages/storybook8/stories/Examples/LocalPreview/snippets/LocalPreviewExample.snippet.tsx
  packages/storybook8/stories/INTERNAL/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
  packages/storybook8/tsconfig.json
  samples/CallWithChat/src/app/theming/SwitchableFluentThemeProvider.tsx
  samples/CallWithChat/src/app/theming/ThemeSelector.tsx
  samples/CallWithChat/src/app/utils/AppUtils.ts
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/CallWithChat/tsconfig.json
  samples/CallWithChat/tsconfig.preprocess.json
  samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx
  samples/Calling/src/app/theming/ThemeSelector.tsx
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/HomeScreen.tsx
  samples/Calling/tsconfig.json
  samples/Calling/tsconfig.preprocess.json
  samples/CallingStateful/tsconfig.json
  samples/CallingStateful/tsconfig.preprocess.json
  samples/Chat/src/app/theming/SwitchableFluentThemeProvider.tsx
  samples/Chat/src/app/theming/ThemeSelector.tsx
  samples/Chat/tsconfig.json
  samples/Chat/tsconfig.preprocess.json
  samples/ComponentExamples/src/examples/RenderSingleVideoTileExample.tsx
  samples/ComponentExamples/src/examples/UseSelectorExample.tsx
  samples/ComponentExamples/src/utils/loadConfigFromUrlQuery.ts
  samples/ComponentExamples/tsconfig.json
Labels: does not need changelog

#5354 [Storybook] Fixing vertical alignment on banner
  packages/storybook8/stories/Composites/CallComposite/Docs.mdx
  packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
Labels: does not need changelog

#5348 Add new remote ufd types
  change-beta/@azure-communication-react-7e6283cb-4c36-41e2-a1e5-699e307a0090.json
  packages/calling-component-bindings/src/utils/callUtils.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/UserFacingDiagnosticsSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#5331 Fix unit test warnings - Ensure tests fail when console warnings and errors are present
  common/config/jest/jestSetup.js
  packages/react-components/jest.config.js
  packages/react-components/jestSetup.ts
  packages/react-components/src/components/Attachment/AttachmentCard.test.tsx
  packages/react-components/src/components/Attachment/AttachmentCardGroup.test.tsx
  packages/react-components/src/components/Attachment/AttachmentDownloadCards.test.tsx
  packages/react-components/src/components/Attachment/AttachmentUploadCards.test.tsx
  packages/react-components/src/components/CameraButton.test.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.test.tsx
  packages/react-components/src/components/Dialpad/Dialpad.test.tsx
  packages/react-components/src/components/EndCallButton.test.tsx
  packages/react-components/src/components/ErrorBar.test.tsx
  packages/react-components/src/components/ImageOverlay.test.tsx
  packages/react-components/src/components/MessageStatusIndicator.test.tsx
  packages/react-components/src/components/MessageThread.test.tsx
  packages/react-components/src/components/MicrophoneButton.test.tsx
  packages/react-components/src/components/ParticipantList.test.tsx
  packages/react-components/src/components/RaiseHandButton.test.tsx
  packages/react-components/src/components/ResponsiveVerticalGallery.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.test.tsx
  packages/react-components/src/components/ScreenShareButton.test.tsx
  packages/react-components/src/components/SendBox.test.tsx
  packages/react-components/src/components/VideoGallery.test.tsx
  packages/react-components/src/components/VideoTile.test.tsx
  packages/react-components/src/components/utils/testUtils.tsx
  packages/react-composites/tests/browser/call/hermetic/HorizontalGalleryResizing.test.ts
  packages/react-composites/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts
Labels: does not need changelog

#5349 Remove start-call-beta conditional-compile statements
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
Labels: does not need changelog

#5352 Make adapter table narrower
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
  packages/storybook8/stories/Composites/Adapters/table.css
Labels: does not need changelog

#4613 Add eslint rule to disallow non-null-assertion
  packages/acs-ui-common/.eslintrc.js
  packages/calling-component-bindings/.eslintrc.js
  packages/calling-stateful-client/.eslintrc.js
  packages/chat-component-bindings/.eslintrc.js
  packages/chat-stateful-client/.eslintrc.js
  packages/communication-react/.eslintrc.js
  packages/fake-backends/.eslintrc.js
  packages/react-components/.eslintrc.js
  packages/react-components/src/components/Survey/TagsSurvey/TagsSurvey.tsx
  packages/react-composites/.eslintrc.js
  packages/react-composites/tests/browser/chat/hermetic/fixture.ts
  packages/storybook8/.eslintrc.js
  samples/CallWithChat/.eslintrc.js
  samples/Calling/.eslintrc.js
  samples/CallingStateful/.eslintrc.js
  samples/Chat/.eslintrc.js
  samples/ComponentExamples/.eslintrc.js
  samples/Server/.eslintrc.js
Labels: does not need changelog

#5337 Resolve A11Y Bug around not focusing on format options toolbar when showing format options.
  change-beta/@azure-communication-react-a85dec19-9bd4-4ac6-8139-0ddb5ea2e43f.json
  change/@azure-communication-react-a85dec19-9bd4-4ac6-8139-0ddb5ea2e43f.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/Toolbar/RichTextToolbar.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5361 [Chat] Bump Chat SDK & Signaling to Latest Stable
  change-beta/@azure-communication-react-27b510f4-06e8-4bad-b2cd-bd161ee4156c.json
  change/@azure-communication-react-27b510f4-06e8-4bad-b2cd-bd161ee4156c.json
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5357 Add verbose for getting errors
  .github/workflows/ci.yml
Labels: does not need changelog

#5363 Fix calling build error, add PR validation to prevent it from happening again
  .github/workflows/ci.yml
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  rush.json
  samples/CallingStateful/package.json
  samples/CallingStateful/src/App.tsx
  samples/CallingStateful/src/utils/AppUtils.ts
  samples/CallingStateful/src/views/Homescreen.tsx
Labels: does not need changelog

#5086 [Storybook] Transition MSDoc Tutorials to Storybook
  packages/storybook8/public/images/call-with-chat-file-sharing-permissions.png
  packages/storybook8/public/images/call-with-chat-inline-image.png
  packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
Labels: does not need changelog

#5356 RTT Component
  change-beta/@azure-communication-react-b47e432f-c070-4915-9066-76577513519a.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/Captions.style.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook8/stories/INTERNAL/RTT/Docs.mdx
  packages/storybook8/stories/INTERNAL/RTT/RealTimeText.story.tsx
  packages/storybook8/stories/INTERNAL/RTT/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RTT/snippets/ExampleRTT.snippet.tsx
  packages/storybook8/stories/controlsUtils.ts
Labels: breaking-change

#5355 RTT Modal Component
  change-beta/@azure-communication-react-193881fb-22bd-4803-ace2-f833e2d4de93.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/RTTModal.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook8/stories/INTERNAL/RTTModal/Docs.mdx
  packages/storybook8/stories/INTERNAL/RTTModal/RTTModal.story.tsx
  packages/storybook8/stories/INTERNAL/RTTModal/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RTTModal/snippets/RTTModal.snippet.tsx
Labels: breaking-change

#5216 Update the reconnecting RemoteUFD according to figma
  change-beta/@azure-communication-react-19050629-62ab-4bee-b9e9-0049c5804676.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/StreamMedia.tsx
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/styles/StreamMedia.styles.ts
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: does not need changelog

#5280 Add bundle size reports to the PR description
  .github/workflows/ci.md
  .github/workflows/ci.yml
Labels: does not need changelog, significant bundle size change

#5364 [JS loaders] update docs for new API
  packages/storybook8/stories/Composites/TypeScriptLoading/Docs.mdx
Labels: does not need changelog

#5366 [a11y][bugfix] Add Close aria label for spotlight prompt
  change-beta/@azure-communication-react-3f2cb505-b6c4-4379-81fb-240ccd1eea31.json
  change-beta/@azure-communication-react-88f67533-e295-47ba-b755-11969a29471e.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/components/Prompt.tsx
  packages/react-composites/src/composites/CallComposite/utils/spotlightUtils.ts
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#5367 Groom changelog beta release beta/1.21.0-beta.1
  packages/communication-react/CHANGELOG.beta.md
Labels: does not need changelog

#5371 [Calling OCE] update SDK and lock file
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5369 Release/1.21.0 beta.1 snapshot update
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-custom-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/CallControls.test.ts-snapshots/call-control-new-experience-injected-buttons-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-button-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-disabled-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/DtmfDialpad.test.ts-snapshots/Dtmf-Dialpad-Hidden-Non-PSTN-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Reactions.test.ts-snapshots/reaction-sub-menu-in-ongoing-call-in-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/Reactions.test.ts-snapshots/reaction-sub-menu-in-ongoing-call-in-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/caption-button-teams-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-disabled-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/default-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/speaker-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/CallControls.test.ts-snapshots/call-with-chat-custom-buttons-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-microphone-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-microphone-screen-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-speaker-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-new-selected-speaker-screen-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-screen-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/MoreDrawer.test.ts-snapshots/call-with-chat-more-drawer-screen-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5379 TDBuild latest localization to release branch for 1.21.0-beta.1
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5372 Allow to add CC in import sentence
  common/scripts/babel-conditional-preprocess.js
Labels: does not need changelog

#5382 Merge prerelease-beta-release-beta/1.21.0-beta.1 to main
  change-beta/@azure-communication-react-19050629-62ab-4bee-b9e9-0049c5804676.json
  change-beta/@azure-communication-react-193881fb-22bd-4803-ace2-f833e2d4de93.json
  change-beta/@azure-communication-react-27b510f4-06e8-4bad-b2cd-bd161ee4156c.json
  change-beta/@azure-communication-react-361438b2-fe57-42c6-979e-621cddbf7602.json
  change-beta/@azure-communication-react-367d1747-182e-425c-a897-cbcdfbc06ecd.json
  change-beta/@azure-communication-react-3770976d-8796-497c-b460-2f38b8b95e39.json
  change-beta/@azure-communication-react-37efe55e-c2bc-4bc4-99d0-c2c933a86333.json
  change-beta/@azure-communication-react-3d3b922a-3c9d-4a69-8480-982d30aec40f.json
  change-beta/@azure-communication-react-43b808a4-0c26-4119-a26b-7d31efbb2b93.json
  change-beta/@azure-communication-react-484c5bd7-e969-4b82-bedb-3dd2bd9fc1a0.json
  change-beta/@azure-communication-react-601fa9cc-a5ef-444f-ba11-fcfbce7c9a70.json
  change-beta/@azure-communication-react-7e6283cb-4c36-41e2-a1e5-699e307a0090.json
  change-beta/@azure-communication-react-801ca892-ab36-4fea-8e73-14919edbf909.json
  change-beta/@azure-communication-react-801d4bf5-46a3-4198-9dd6-6724c7eff2c3.json
  change-beta/@azure-communication-react-839f12bb-f1d6-43dc-9ba8-41fc6b17baaf.json
  change-beta/@azure-communication-react-9027708a-39a4-4de9-bc14-a6f55681f927.json
  change-beta/@azure-communication-react-95db09fa-bca5-48f4-b7be-bf7cd4a97ed2.json
  change-beta/@azure-communication-react-a85dec19-9bd4-4ac6-8139-0ddb5ea2e43f.json
  change-beta/@azure-communication-react-a9fb84d9-5a0a-43a1-b407-decf5c80312c.json
  change-beta/@azure-communication-react-b47e432f-c070-4915-9066-76577513519a.json
  change-beta/@azure-communication-react-b7391df0-c3f4-490f-84ad-b97252d3a49d.json
  change-beta/@azure-communication-react-c5b508a6-370f-414d-9663-905d1ef3f69b.json
  change-beta/@azure-communication-react-cb854d3f-732e-4c9a-8156-dc31df49ad74.json
  change-beta/@azure-communication-react-d5d89289-b2e5-4af7-8ae6-b7f148d46345.json
  change-beta/@azure-communication-react-deda54f5-fac2-4f69-82ac-ac90b00c63f7.json
  change-beta/@azure-communication-react-e92f5533-95b3-432c-82dc-413ac8ac6662.json
  change-beta/@azure-communication-react-ebad70bc-6036-4b67-b5f9-438a20702e0e.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog
