Repository Azure/communication-ui-library, pull requests merged in 2024-12, with the labels that each got.

#5455 Add chat component bindings tests
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/chat-component-bindings/package.json
  packages/chat-component-bindings/src/baseSelectors.test.ts
  packages/chat-component-bindings/src/chatParticipantListSelector.test.ts
  packages/chat-component-bindings/src/errorBarSelector.test.ts
  packages/chat-component-bindings/src/handlers/createHandlers.test.ts
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/chat-component-bindings/src/messageThreadSelector.test.ts
  packages/chat-component-bindings/src/messageThreadSelector.ts
  packages/chat-component-bindings/src/providers/ChatClientProvider.test.tsx
  packages/chat-component-bindings/src/providers/ChatThreadClientProvider.test.tsx
  packages/chat-component-bindings/src/sendBoxSelector.test.ts
  packages/chat-component-bindings/src/utils/compareMessages.test.ts
  packages/chat-component-bindings/src/utils/compareMessages.ts
  packages/chat-component-bindings/src/utils/getImageAttachmentsFromHTMLContent.test.ts
  packages/chat-component-bindings/src/utils/getImageAttachmentsFromHTMLContent.ts
  packages/chat-component-bindings/src/utils/memoizeFnAll.ts
Labels: does not need changelog

#5462 Revert changes to add undefined return type so we are not introducing breaking change
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/common/AvatarPersona.tsx
Labels: breaking-change, does not need changelog

#5471 TDBuild latest localization
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5460 Stablize Caption Banner component
  change-beta/@azure-communication-react-050e392e-7a15-4f97-8415-a0b53cc93fda.json
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/Caption.tsx
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/storybook8/stories/Components/CaptionsBanner/CaptionsBanner.story.tsx
  packages/storybook8/stories/Components/CaptionsBanner/Docs.mdx
  packages/storybook8/stories/Components/CaptionsBanner/index.stories.tsx
  packages/storybook8/stories/Components/CaptionsBanner/mockCaptions.ts
  packages/storybook8/stories/Components/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
Labels: breaking-change

#5461 Revert changes to add undefined return type so we are not introducing breaking change
  change-beta/@azure-communication-react-39c6d06e-a84f-4a3e-a934-a259cf7d3334.json
  change/@azure-communication-react-39c6d06e-a84f-4a3e-a934-a259cf7d3334.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-composites/src/composites/common/AvatarPersona.tsx
Labels: breaking-change

#5481 Fix release verison from 1.23 to 1.22
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5480 Fix release version from 1.23 to 1.22
  packages/acs-ui-common/package.json
  packages/acs-ui-common/src/telemetryVersion.js
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5477 Resize VideoGallery in snapshots tests to avoid flaky scrollbars
  common/config/playwright/playwright.config.common.ts
  packages/react-components/tests/browser/VideoGallery.spec.tsx
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-1-videogallery-with-audio-only-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-1-2-videogallery-with-audio-only-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-1-videogallery-with-some-video-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-2-2-videogallery--with-some-video-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-1-videogallery-with-screen-share-before-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-3-2-videogallery-with-screen-share-after-dominant-speakers-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-1-videogallery-before-spotlight-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/stable/VideoGallery.spec.tsx-snapshots/VGL-4-2-videogallery-after-spotlight-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5437 Hardmute - Integrate new change from web sdk - Part 3
  change-beta/@azure-communication-react-dc5bcef5-37fa-4bec-a2e7-745dd9895f4a.json
  change/@azure-communication-react-dc5bcef5-37fa-4bec-a2e7-745dd9895f4a.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CapabilitiesSubscriber.ts
  packages/calling-stateful-client/src/MediaAccessSubscriber.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/types/VideoGalleryParticipant.ts
Labels: breaking-change

#5478 Update dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
Labels: does not need changelog

#5482 Updated apis naming
  change-beta/@azure-communication-react-ef662390-7805-4021-aeb9-6ef54b8aae91.json
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/index.ts
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
Labels: breaking-change

#5491 Revert Jest Test changes
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
Labels: does not need changelog

#5484 [Storybook] Remove the term bot from chat docs
  packages/storybook8/stories/Composites/CallWithChatComposite/snippets/Server.snippet.tsx
  packages/storybook8/stories/Composites/ChatComposite/ATryChatComposite.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/BasicExample.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/CustomBehavior.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/CustomDataModelExample.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/CustomDateTimeFormat.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/RichTetEditorExample.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/ThemesExample.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/snippets/ATryChatCompositeContainer.snippet.tsx
  packages/storybook8/stories/Composites/ChatComposite/snippets/CustomDataModelExampleContainer.snippet.tsx
  packages/storybook8/stories/Composites/ChatComposite/snippets/Utils.tsx
  packages/storybook8/stories/Concepts/TeamsInterop/utils/controlsUtils.ts
  packages/storybook8/stories/controlsUtils.ts
Labels: does not need changelog

#5479 Storybook doc for starting captions in the background
  packages/storybook8/stories/Concepts/ClosedCaptions/Doc.mdx
  packages/storybook8/stories/Concepts/ClosedCaptions/snippets/ClosedCaptions.snippet.tsx
Labels: does not need changelog

#5494 Added checks for chat attachments UI tests
  packages/react-components/tests/browser/ChatMyMessageComponent.spec.tsx
Labels: does not need changelog

#5473 Update string translations doc
  docs/references/string-translations.md
Labels: does not need changelog

#5498 Fixed broken link to video gallery storybook page
  packages/storybook8/stories/Components/Overview.mdx
Labels: does not need changelog

#5497 Fixed flaky chat message tests
  packages/react-components/tests/browser/ChatMyMessageComponent.spec.tsx
  packages/react-components/tests/browser/ChatMyMessageComponentKeyboardNavigationTests.spec.tsx
Labels: does not need changelog

#5469 Make Captions Setting Modal a public component
  change-beta/@azure-communication-react-748047cf-fe00-4578-9848-744d0b50d402.json
  change-beta/@azure-communication-react-d41d360f-8f6b-4aac-942f-1f41b3ff70f9.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/CaptionsSettingsModal.tsx
  packages/react-components/src/components/RTTModal.tsx
  packages/react-components/src/components/StartCaptionsButton.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/index.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/types/CaptionsAvailableLanguageStrings.ts
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/react-composites/src/composites/common/CallingCaptionsSettingsModal.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/Drawer/CaptionLanguageSettingsDrawer.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/Drawer/SpokenLanguageSettingsDrawer.tsx
  packages/react-composites/src/composites/common/StarSurvey.tsx
  packages/react-composites/src/composites/common/TagsSurvey.tsx
  packages/storybook8/stories/Components/CaptionsSettingsModal/CaptionsSettingsModal.story.tsx
  packages/storybook8/stories/Components/CaptionsSettingsModal/Docs.mdx
  packages/storybook8/stories/Components/CaptionsSettingsModal/index.stories.tsx
  packages/storybook8/stories/Components/CaptionsSettingsModal/snippets/CaptionsSettingsModal.snippet.tsx
  packages/storybook8/stories/INTERNAL/CaptionsSettingsModal/index.stories.tsx
  packages/storybook8/stories/INTERNAL/CaptionsSettingsModal/snippets/CaptionsSettingsModal.snippet.tsx
Labels: breaking-change, significant bundle size change

#5499 Make Start Captions Button a public component
  change-beta/@azure-communication-react-d99c1613-8313-4b8f-bbf5-2cd3c8365e2f.json
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/StartCaptionsButton.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/common/CaptionsBannerMoreButton.tsx
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/storybook8/stories/Components/StartCaptionsButton/Docs.mdx
  packages/storybook8/stories/Components/StartCaptionsButton/StartCaptionsButton.story.tsx
  packages/storybook8/stories/Components/StartCaptionsButton/index.stories.tsx
  packages/storybook8/stories/Components/StartCaptionsButton/snippets/StartCaptionsButton.snippet.tsx
Labels: breaking-change

#5500 [BugFix] Ensure image overlay announces as image details
  change-beta/@azure-communication-react-31153022-b68a-433b-87c3-d55c675d6e37.json
  change/@azure-communication-react-31153022-b68a-433b-87c3-d55c675d6e37.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ImageOverlay.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5504 Update pnpm-lock.yaml for stable
  common/config/rush/variants/stable/pnpm-lock.yaml
Labels: does not need changelog

#5506 Groom changelog stable remove beta suffix/1.22.0
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#5501 removing documentation which hints that communication as a Teams user…
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
  packages/storybook8/stories/Concepts/CommunicationAsTeamsUser/Docs.mdx
Labels: does not need changelog

#5507 [Storybook] Fix storybook Unsupported Browser canvas padding
  packages/storybook8/stories/Components/UnsupportedBrowser/Docs.mdx
Labels: does not need changelog

#5489 updated together mode subscriber and included notification when toget…
  change-beta/@azure-communication-react-c1ee22c0-c21c-4cbf-a607-2c5b657f1910.json
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/TogetherModeSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5505 TDBuild latest localization
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5511 TDBuild latest localization on release branch
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5510 Fixed flaky RTE tests
  common/config/playwright/playwright.config.common.ts
  packages/react-components/tests/browser/ChatMessageComponentAsRichTextEditBox.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponent.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponentTablesTests.spec.tsx
  packages/react-components/tests/browser/RichTextSendBox.spec.tsx
Labels: does not need changelog

#5509 [Storybook] sb beta banner cleanup
  packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
  packages/storybook8/stories/Concepts/ClosedCaptions/Doc.mdx
Labels: does not need changelog

#5513 Cnwankwo/together mode icon
  change-beta/@azure-communication-react-55eea048-2762-4ad5-8234-6d781978a2fe.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/common/icons.tsx
Labels: significant bundle size change

#5514 Flaky UI components tests fix part 2
  packages/react-components/tests/README.md
  packages/react-components/tests/browser/Attachment.spec.tsx
  packages/react-components/tests/browser/ChatMessageComponentAsRichTextEditBox.spec.tsx
  packages/react-components/tests/browser/ImageOverlay.spec.tsx
  packages/react-components/tests/browser/MessageThread.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponent.spec.tsx
  packages/react-components/tests/browser/RichTextInputBoxComponentTablesTests.spec.tsx
  packages/react-components/tests/browser/RichTextInsertTablePane.spec.tsx
  packages/react-components/tests/browser/RichTextSendBox.spec.tsx
  packages/react-components/tests/browser/VideoGallery.spec.tsx
  packages/react-components/tests/browser/utils/RichTextEditorUtils.tsx
Labels: breaking-change, does not need changelog

#5516 Reference communication-chat instead of communication-signaling where possible.
  packages/fake-backends/src/ThreadEventEmitter.ts
Labels: does not need changelog

#5519 [Storybook] clean up adapters page
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
Labels: does not need changelog

#5452 Origin/fuyan/hard mute UI components changes - part 5
  change-beta/@azure-communication-react-770df296-e84b-4925-9152-a8832b309a65.json
  change-beta/@azure-communication-react-c0b634e9-dc8d-4ecb-9d78-940517f2f5dc.json
  change/@azure-communication-react-770df296-e84b-4925-9152-a8832b309a65.json
  change/@azure-communication-react-c0b634e9-dc8d-4ecb-9d78-940517f2f5dc.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-component-bindings/src/participantListSelector.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/LocalVideoTile.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/LocalScreenShare.tsx
  packages/react-components/src/components/VideoGallery/useVideoStreamLifecycleMaintainer.ts
  packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/ParticipantListParticipant.ts
  packages/react-components/src/types/VideoGalleryParticipant.ts
  packages/react-components/tests/browser/VideoGallery.spec.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/CapabilitiesChangedNotificationBar.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
Labels: breaking-change, significant bundle size change

#5521 [Calling Sample Cleanup] remove empty lines
  samples/Calling/src/app/App.tsx
  samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx
  samples/Calling/src/app/theming/ThemeSelector.tsx
  samples/Calling/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/Footer.tsx
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: does not need changelog

#5523 [Storybook] Fixing the styling of the Survey page to be consistent
  packages/storybook8/stories/Concepts/Survey/Doc.mdx
  packages/storybook8/stories/Concepts/Survey/Survey.story.tsx
  packages/storybook8/stories/Concepts/Survey/index.stories.tsx
Labels: does not need changelog

#5503 Update storybook snippets to how to use the components with usePropsFor
  packages/storybook8/stories/Components/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
  packages/storybook8/stories/Components/CaptionsSettingsModal/snippets/CaptionsSettingsModal.snippet.tsx
  packages/storybook8/stories/Components/StartCaptionsButton/snippets/StartCaptionsButton.snippet.tsx
Labels: does not need changelog

#5525 Real Time Text Component Related Changes and Strings
  change-beta/@azure-communication-react-26cb5aca-ad5e-425a-ba56-349c49b5c9ed.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RTTDisclosureBanner.tsx
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/components/StartRealTimeTextButton.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/RTTDisclosureBanner.styles.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#5528 Rename RTT to RealTimeText
  change-beta/@azure-communication-react-f5b7088d-a3d8-47ed-8b8a-289d4fdd0f5d.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/components/RealTimeTextModal.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook8/stories/INTERNAL/RTT/Docs.mdx
  packages/storybook8/stories/INTERNAL/RTTModal/Docs.mdx
  packages/storybook8/stories/INTERNAL/RealTimeText/Docs.mdx
  packages/storybook8/stories/INTERNAL/RealTimeText/RealTimeText.story.tsx
  packages/storybook8/stories/INTERNAL/RealTimeText/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RealTimeText/snippets/ExampleRealTimeText.snippet.tsx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/Docs.mdx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/RealTimeTextModal.story.tsx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/snippets/RealTimeTextModal.snippet.tsx
Labels: breaking-change

#5527 RTT disclosure banner should be a private component
  change-beta/@azure-communication-react-67208b90-93d8-44b7-8165-4fb34611474d.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RTTDisclosureBanner.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/storybook8/stories/INTERNAL/RTTDisclosureBanner/Docs.mdx
  packages/storybook8/stories/INTERNAL/RTTDisclosureBanner/RTTDisclosureBanner.story.tsx
  packages/storybook8/stories/INTERNAL/RTTDisclosureBanner/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RTTDisclosureBanner/snippets/RTTDisclosureBanner.snippet.tsx
Labels: breaking-change
