Repository Azure/communication-ui-library, pull requests merged in 2024-09, with the labels that each got.

#5087 Fix react render tracker
  samples/CallWithChat/public/index.html
  samples/CallWithChat/src/app/utils/AppUtils.ts
  samples/CallWithChat/src/index.tsx
  samples/Calling/public/index.html
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/HomeScreen.tsx
  samples/Calling/src/index.tsx
  samples/Chat/public/index.html
  samples/Chat/src/app/utils/utils.ts
  samples/Chat/src/index.tsx
Labels: does not need changelog

#5118 [Inbound-outbound] remove beta banners from storybook
  packages/storybook/stories/CallComposite/Quickstart1ToNDocs.stories.mdx
  packages/storybook/stories/CallComposite/QuickstartPSTNDocs.stories.mdx
  packages/storybook/stories/Dialpad/Dialpad.stories.tsx
  packages/storybook8/stories/Composites/CallComposite/1ton/Docs.mdx
  packages/storybook8/stories/Composites/CallComposite/pstn/Docs.mdx
Labels: does not need changelog

#5116 [Chat] Fixed ChatComposite Storybook Issues for V8
  packages/storybook8/stories/Composites/ChatComposite/CustomBehavior.stories.tsx
  packages/storybook8/stories/Composites/ChatComposite/Docs.mdx
  packages/storybook8/stories/constants.ts
Labels: does not need changelog

#5135 [Release] 1.19.0 beta.3 branch setup
  packages/acs-ui-common/package.json
  packages/acs-ui-common/src/telemetryVersion.js
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/snapshots/beta/StaticHtmlComposites/CompositeJavascriptTest.test.ts-snapshots/chatCompositeHtmlCheck-chromium-linux.png
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5139 [Release]Groom changelog/1.19.0 beta.3
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/fake-backends/CHANGELOG.json
  packages/react-components/CHANGELOG.json
  packages/react-composites/CHANGELOG.json
  packages/storybook/CHANGELOG.json
  packages/storybook8/CHANGELOG.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-typescript-regression/CHANGELOG.json
Labels: does not need changelog

#5145 Conceptual docs for DNS
  change-beta/@azure-communication-react-8459fb2d-5be8-42dc-9060-f1eb6a12407a.json
  packages/storybook8/public/images/DNS-off.png
  packages/storybook8/public/images/DNS-on.png
  packages/storybook8/stories/Concepts/DeepNoiseSuppression/Docs.mdx
Labels: breaking-change

#5106 [JavaScript-loaders] Add loader path import on communication-react for JS Composite loader functions
  change-beta/@azure-communication-react-1aef335a-42b6-4070-9763-a0bc86f54ade.json
  change-beta/@azure-communication-react-4be604d9-5c4f-41fe-8fd4-cef3a57d8d48.json
  packages/acs-ui-javascript-loaders/jest.config.js
  packages/acs-ui-javascript-loaders/package.json
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
  packages/communication-react/api-extractor-complete.json
  packages/communication-react/api-extractor-complete.stable.json
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/api-summary.ts
  packages/communication-react/src/index.ts
  packages/communication-react/src/javascript-loaders.ts
  packages/storybook8/stories/Examples/CustomButtonInjection/Docs.mdx
  packages/storybook8/stories/Examples/CustomButtonInjection/snippets/CustomButtonImages.tsx
Labels: breaking-change

#5160 [js-loaders] api by flavor fix
  packages/communication-react/package.json
Labels: does not need changelog

#5163 [Ezra bug] Fix issue where end call button shifts to left
  packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
Labels: does not need changelog

#5167 Update SDK ref for DNS
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
Labels: documentation, does not need changelog

#5172 [JS-loaders] fix test mock imports
  packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx
  packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
Labels: does not need changelog

#5169 Changelog update for text only messaging policy
  packages/communication-react/CHANGELOG.beta.md
Labels: does not need changelog

#5162 [A11y][Test] Added keyboard navigation tests for ChatMyMessage component
  packages/react-components/src/components/ChatMessage/ChatMessageActionMenu.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageActionsFlyout.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/MessageThread.test.tsx
  packages/react-components/tests/browser/ChatMyMessageComponent.spec.tsx
  packages/react-composites/tests/browser/chat/hermetic/ErrorBar.test.ts
  packages/react-composites/tests/browser/chat/hermetic/ReadReceipt.test.ts
  packages/react-composites/tests/browser/common/hermeticChatTestHelpers.ts
  packages/react-composites/tests/browser/common/utils.ts
Labels: does not need changelog

#5178 Address arb comments from 1.19.0
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
Labels: breaking-change

#5175 [Feature cleanup] remove cc for hide attendee names
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/participantListSelector.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CapabilitiesSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CapabilitiesChangedNotificationBar.tsx
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
Labels: does not need changelog

#5192 Ensure all sample links are relative and not pointed at the root route
  samples/CallWithChat/src/app/utils/AppUtils.ts
  samples/CallWithChat/src/app/utils/ShakeToSendLogs.tsx
  samples/CallWithChat/src/app/utils/createThread.ts
  samples/CallWithChat/src/app/utils/credential.ts
  samples/CallWithChat/src/app/utils/getEndpointUrl.ts
  samples/CallWithChat/src/app/utils/joinThread.ts
  samples/CallWithChat/src/app/utils/refreshToken.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/App.tsx
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/utils/ShakeToSendLogs.tsx
  samples/Calling/src/app/utils/credential.ts
  samples/Calling/src/app/views/CallScreen.tsx
  samples/CallingStateful/src/utils/AppUtils.ts
  samples/CallingStateful/src/utils/credential.ts
  samples/Chat/src/app/App.tsx
  samples/Chat/src/app/utils/ShakeToSendLogs.tsx
  samples/Chat/src/app/utils/createThread.ts
  samples/Chat/src/app/utils/credential.ts
  samples/Chat/src/app/utils/emojiCache.ts
  samples/Chat/src/app/utils/getEndpointUrl.ts
  samples/Chat/src/app/utils/getToken.ts
  samples/Chat/src/app/utils/joinThread.ts
  samples/Chat/src/app/utils/refreshToken.ts
  samples/Chat/src/app/utils/setEmoji.ts
  samples/ComponentExamples/src/utils/getEndpointUrl.ts
  samples/ComponentExamples/src/utils/getToken.ts
  samples/StaticHtmlComposites/src/service.js
Labels: does not need changelog

#5197 Pull in 5195
  common/scripts/install-run-rush-pnpm.js
  common/scripts/install-run-rush.js
  common/scripts/install-run-rushx.js
  common/scripts/install-run.js
  rush.json
Labels: does not need changelog

#5190 [outbound calling] remove 1-n-calling cc
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/incomingCallStackSelector.ts
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-stateful-client/src/CallAgentDeclarative.test.ts
  packages/calling-stateful-client/src/CallAgentDeclarative.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/TeamsCallAgentDeclarative.ts
  packages/calling-stateful-client/src/TypeGuards.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/IncomingCallNotification.tsx
  packages/react-components/src/components/IncomingCallStack.tsx
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.ts
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/OnRender.ts
  packages/react-components/src/types/VideoGalleryParticipant.ts
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
  packages/react-composites/src/composites/CallComposite/components/HoldPane.tsx
  packages/react-composites/src/composites/CallComposite/pages/HoldPage.tsx
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/common/AvatarPersona.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
  packages/react-composites/tests/browser/call/hermetic/LobbyScreen.test.ts
  packages/react-composites/tests/browser/call/hermetic/PeoplePane.test.ts
  samples/CallWithChat/src/app/views/HomeScreen.tsx
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/HomeScreen.tsx
  samples/CallingStateful/src/App.tsx
  samples/CallingStateful/src/views/CallScreen.tsx
  samples/CallingStateful/src/views/Homescreen.tsx
  samples/CallingStateful/src/views/Login.tsx
Labels: does not need changelog

#5177 Added deprecation note for dataUIId selector util function for Playwright tests
  packages/react-composites/tests/browser/common/utils.ts
Labels: does not need changelog

#5191 [outbound calling] Teams adhoc call cc rm
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createHandlers.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  samples/Calling/src/app/utils/AppUtils.ts
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: does not need changelog

#5213 [ bug fix Compliance issue ] remove Node-static
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/chat-stateful-client/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/globalSetup.ts
  samples/tests/package.json
Labels: does not need changelog

#5203 Fix for the changelog job to compare changelog files between base and main branches correctly
  .github/workflows/ci.yml
Labels: does not need changelog

#5209 [Inbound Calling] Migrate to SB 8
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/storybook8/package.json
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/Docs.mdx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/IncomingCallNotification.story.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/index.stories.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/snippets/IncomingCallNotification.snippet.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/snippets/IncomingCallNotificationStyling.snippet.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallStack/Docs.mdx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallStack/IncomingCallStack.story.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallStack/index.stories.tsx
  packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallStack/snippets/IncomingCallStack.snippet.tsx
  packages/storybook8/stories/Concepts/InboundCalling/Docs.mdx
  packages/storybook8/stories/Concepts/InboundCalling/snippets/IncomingCallStackPropsExample.snippet.tsx
  packages/storybook8/stories/controlsUtils.ts
Labels: does not need changelog

#5218 [OCE] Rush Version Bump
  rush.json
Labels: does not need changelog

#5217 [1.20.0-beta.1 release] TDBuild latest localization
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
Labels: does not need changelog

#5221 [JS-loaders] beta js-loaders
  common/config/babel/features.js
Labels: does not need changelog

#5224 [js-loaders] fix beta-release build
  packages/communication-react/tsconfig.preprocess.json
Labels: does not need changelog

#5220 Ensure storybook 8 builds with default build commands and do not generate s6 PR links
  .github/workflows/ci.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/publish-chromatic.yml
  packages/storybook8/package.json
Labels: does not need changelog

#5226 [JS-loaders] Change files for release
  change-beta/@azure-communication-react-2c0921c2-fcd8-49c7-86f3-88339f1caa54.json
Labels: does not need changelog
