Repository Azure/communication-ui-library, pull requests merged in 2024-06, with the labels that each got.

#4674 Fixed how margin is added for attachmentCardBaseStyles
  packages/react-components/src/components/styles/AttachmentCardGroup.styles.ts
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-acs-message-single-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-custom-actions-clicked-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-mymessage-single-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/Attachment.spec.tsx-snapshots/attachment-in-messagethread-teams-message-single-Mobile-Android-Portrait-linux.png
Labels: do not need changelog

#4684 Update Calling beta to 1.26.1-beta.1 and stable to 1.25.1
  change-beta/@azure-communication-react-fa4393f1-dad8-4092-996c-b011b08b1f53.json
  change/@azure-communication-react-fa4393f1-dad8-4092-996c-b011b08b1f53.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change

#4689 [Chat] Updated CC flags for File Sharing GA Release
  change-beta/@azure-communication-react-c0e49cb4-b496-4ab7-afe8-8b922bbf97f0.json
  change/@azure-communication-react-c0e49cb4-b496-4ab7-afe8-8b922bbf97f0.json
  common/config/babel/features.js
  packages/acs-ui-common/src/common.ts
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/chat-component-bindings/src/messageThreadSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/Attachment/AttachmentDownloadCards.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MessageComponents/FluentChatMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.test.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/SendBox.styles.ts
  packages/react-components/src/components/utils/ChatMessageComponentAsEditBoxUtils.test.tsx
  packages/react-components/src/components/utils/ChatMessageComponentAsEditBoxUtils.tsx
  packages/react-components/src/components/utils/ChatMessageComponentUtils.tsx
  packages/react-components/src/components/utils/SendBoxUtils.test.ts
  packages/react-components/src/components/utils/SendBoxUtils.ts
  packages/react-components/src/components/utils/common.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/Attachment.ts
  packages/react-components/src/types/ChatMessage.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/ChatComposite/Strings.tsx
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts
  packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUploadButton.tsx
  packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts
  packages/react-composites/src/composites/ChatComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/tests/browser/chat/hermetic/AttachmentSharing.test.ts
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Chat/src/app/ChatScreen.tsx
  samples/Chat/src/app/utils/downloadHandler.tsx
  samples/Chat/src/app/utils/uploadHandler.ts
Labels: breaking-change

#4696 Add on paste callback for handling pasting in rich text send and edit boxes
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.test.tsx
  packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
  packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/index.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx
  packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
  packages/react-composites/src/composites/common/SendBoxPicker.tsx
  packages/storybook/stories/MessageThread/MessageThread.stories.tsx
  packages/storybook/stories/MessageThread/snippets/WithRichTextEditor.snippet.tsx
  samples/Chat/src/app/ChatScreen.tsx
Labels: breaking-change, do not need changelog

#4637 Ruslanz/meeting coordinates composite
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.test.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/package.json
  packages/react-components/src/components/MeetingConferencePhoneInfo.test.tsx
  packages/react-components/src/components/MeetingConferencePhoneInfo.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/TeamsMeetingConferenceInfo.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
Labels: breaking-change

#4700 [Bugfix] Add camera button to videoTile page
  packages/storybook/stories/Styling/snippets/StylingVideoTile.snippet.tsx
  packages/storybook/stories/utils.ts
Labels: do not need changelog

#4715 Dependencies update
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
Labels: do not need changelog

#4724 Add createdBy to ChatThreadProperties for RTE Image upload
  packages/chat-stateful-client/src/ChatClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
Labels: breaking-change

#4699 Add pinning functionality in participant list
  change-beta/@azure-communication-react-c04a6396-cb1f-4bab-a89e-df7d7ba8f3d8.json
  change/@azure-communication-react-c04a6396-cb1f-4bab-a89e-df7d7ba8f3d8.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/common/ParticipantContainer.tsx
  packages/react-composites/src/composites/common/PeoplePaneContent.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-remove-participant-presenter-Mobile-Android-Portrait-linux.png
Labels: breaking-change

#4717 [Chat] Version bump of communication-chat
  change-beta/@azure-communication-react-e876500f-d7d5-4dd5-a356-93edfa7882ef.json
  change/@azure-communication-react-e876500f-d7d5-4dd5-a356-93edfa7882ef.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/chat-component-bindings/package.json
  packages/chat-component-bindings/src/messageThreadSelector.ts
  packages/chat-stateful-client/package.json
  packages/chat-stateful-client/src/EventSubscriber.ts
  packages/chat-stateful-client/src/TestHelpers.ts
  packages/chat-stateful-client/src/convertChatMessage.ts
  packages/chat-stateful-client/src/mocks/createMockChatThreadClient.ts
  packages/chat-stateful-client/src/types/ChatMessageWithStatus.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/fake-backends/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change

#4718 Ruslanz/meeting coordinates lost connection
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/useMeetingPhoneInfo.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/Drawer/PreparedMoreDrawer.tsx
  packages/react-composites/src/composites/common/MeetingPhoneInfoPaneContent.tsx
  packages/react-composites/src/composites/common/styles/TeamsMeetingConferenceInfo.style.ts
Labels: breaking-change

#4738 [OCE] update deps 06-14
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
  tools/check-treeshaking/package.json
Labels: do not need changelog

#4739 [Release docs] add note about package.json being point of determination for bump type
  docs/releases/creating-a-release.md
Labels: do not need changelog

#4752 [CTE] Stateful client TeamsCallAgent fixes
  change-beta/@azure-communication-react-d0ba3184-3d0c-42fe-8f35-a1b0f297582c.json
  change/@azure-communication-react-d0ba3184-3d0c-42fe-8f35-a1b0f297582c.json
  packages/calling-stateful-client/src/BetaToStableTypes.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/TeamsCallAgentDeclarative.ts
  packages/calling-stateful-client/src/TypeGuards.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/calling-stateful-client/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/createHandlers.ts
Labels: breaking-change

#4775 Update available patch dependencies for `@azure/communication-react`
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: do not need changelog

#4776 Update react minor versions
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/react-composites/src/composites/CallComposite/utils/MediaGalleryUtils.test.tsx
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
Labels: do not need changelog

#4773 Fix build action names with hashes in CI action
  .github/workflows/ci.yml
Labels: do not need changelog

#4781 [Bugfix] stale page update in the Calling samples
  packages/storybook/stories/Troubleshooting.stories.mdx
  samples/CallWithChat/src/app/views/CallScreen.tsx
  samples/Calling/src/app/views/CallCompositeContainer.tsx
Labels: do not need changelog

#4785 [Chat] Update Chat SDK to Beta.3
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-composites/package.json
  packages/storybook/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: do not need changelog

#4780 Change NotificationBar to Notification, and Notifications to NotificationStack
  change-beta/@azure-communication-react-0b63aa3a-08d4-4097-98d4-2028e0e7175a.json
  packages/calling-component-bindings/src/errorNotificationStackSelector.ts
  packages/calling-component-bindings/src/index.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/Notification.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/VideoEffects/VideoBackgroundEffectsPicker.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/Notification.styles.ts
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/BadNetworkQualityNotificationBar.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/useVideoEffectsPane.tsx
  packages/react-composites/src/composites/common/VideoEffectsPane.tsx
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-config-screen-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-config-screen-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-side-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-side-pane-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-blur-camera-on-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-camera-on-custom-background-1-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-camera-on-custom-background-2-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-error-side-pane-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-blur-selected-camera-on-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-camera-on-custom-background-1-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-camera-on-custom-background-2-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-config-screen-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-config-screen-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-side-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/custom-video-effects-side-pane-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-blur-camera-on-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-camera-on-custom-background-1-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-camera-on-custom-background-2-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-config-screen-warning-camera-off-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-error-side-pane-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-blur-selected-camera-on-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-camera-on-custom-background-1-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-camera-on-custom-background-2-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-none-selected-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/VideoEffects.test.ts-snapshots/video-effects-side-pane-warning-camera-off-Desktop-Chrome-linux.png
  packages/storybook/stories/INTERNAL/NotificationBar/Notification.stories.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/NotificationStack.stories.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotification.snippet.tsx
  packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotificationStack.snippet.tsx
Labels: breaking-change

#4789 Add soft mute notifications
  packages/calling-component-bindings/src/errorBarSelector.ts
  packages/calling-component-bindings/src/index.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/ErrorBar.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
Labels: breaking-change

#4784 remove notification
  packages/calling-component-bindings/src/errorBarSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/MeetingConferencePhoneInfo.test.tsx
  packages/react-components/src/components/MeetingConferencePhoneInfo.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/BadNetworkQualityNotificationBar.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/NetworkReconnectTile.tsx
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/common/MeetingPhoneInfoPaneContent.tsx
Labels: breaking-change

#4791 Notification for speaking while muted
  packages/calling-component-bindings/src/hooks/usePropsFor.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/HoldPage.tsx
  packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx
  packages/react-composites/src/composites/CallComposite/styles/CallPage.styles.ts
  packages/react-composites/src/composites/CallComposite/types/ErrorTracking.ts
  packages/react-composites/src/composites/CallComposite/utils/TrackErrors.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/banner-when-speaking-while-muted-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/UserFacingDiagnostics.test.ts-snapshots/error-bar-microphone-stops-unexpectedly-Mobile-Android-Portrait-linux.png
  packages/storybook/stories/controlsUtils.ts
Labels: breaking-change
