Repository Azure/communication-ui-library, pull requests merged in 2025-01, with the labels that each got.

#5539 Hard mute accessibility
  change-beta/@azure-communication-react-02e14d41-7b7c-4a6f-9612-c1396c8e098e.json
  change/@azure-communication-react-02e14d41-7b7c-4a6f-9612-c1396c8e098e.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5542 [bugfix] Add missing cc code for media-access and resolve new ts lint requirement for constant file name
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/chat-stateful-client/src/ChatContext.ts
  packages/chat-stateful-client/src/StatefulChatClient.test.ts
  packages/chat-stateful-client/src/constants.ts
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/utils.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
Labels: does not need changelog

#5536 [bugfix] fix displayName cc from CTE
  samples/Calling/src/app/views/HomeScreen.tsx
Labels: does not need changelog

#5545 [Calling OCE] update stable calling version
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5557 Remove together mode api
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/common/icons.tsx
Labels: does not need changelog

#5555 Component changes for Real Time Text
  change-beta/@azure-communication-react-ac416b4b-9be8-49b1-8e61-31a89b90e73b.json
  change/@azure-communication-react-e4791dc2-7f02-4b0d-9147-ca8b52f51701.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/components/RealTimeTextModal.tsx
  packages/react-components/src/components/StartRealTimeTextButton.tsx
  packages/react-components/src/components/utils/sortCaptionsAndRealTimeTexts.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/common/CallingRealTimeTextModal.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/storybook8/stories/Components/CaptionsBanner/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RealTimeText/RealTimeText.story.tsx
  packages/storybook8/stories/INTERNAL/RealTimeText/index.stories.tsx
  packages/storybook8/stories/INTERNAL/RealTimeText/snippets/ExampleRealTimeText.snippet.tsx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/RealTimeTextModal.story.tsx
  packages/storybook8/stories/INTERNAL/RealTimeTextModal/snippets/RealTimeTextModal.snippet.tsx
Labels: breaking-change

#5540 Live announcement update when a message is received/edited from/by other users
  change-beta/@azure-communication-react-92d6175e-e981-4378-a9ac-0541a5d0ff1a.json
  change/@azure-communication-react-92d6175e-e981-4378-a9ac-0541a5d0ff1a.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5567 TDBuild latest localization
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
  packages/react-composites/src/composites/localization/locales/ar-SA/strings.json
  packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json
  packages/react-composites/src/composites/localization/locales/cy-GB/strings.json
  packages/react-composites/src/composites/localization/locales/de-DE/strings.json
  packages/react-composites/src/composites/localization/locales/en-GB/strings.json
  packages/react-composites/src/composites/localization/locales/es-ES/strings.json
  packages/react-composites/src/composites/localization/locales/es-MX/strings.json
  packages/react-composites/src/composites/localization/locales/fi-FI/strings.json
  packages/react-composites/src/composites/localization/locales/fr-CA/strings.json
  packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
  packages/react-composites/src/composites/localization/locales/he-IL/strings.json
  packages/react-composites/src/composites/localization/locales/it-IT/strings.json
  packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
  packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
  packages/react-composites/src/composites/localization/locales/nb-NO/strings.json
  packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
  packages/react-composites/src/composites/localization/locales/pl-PL/strings.json
  packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
  packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
  packages/react-composites/src/composites/localization/locales/sv-SE/strings.json
  packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
  packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
  packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5558 Updated together mode CC
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/common/icons.tsx
Labels: does not need changelog

#5550 Dependency updates
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  common/scripts/install-run.js
  packages/calling-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-click-more-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-devices-Attendee-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-devices-Attendee-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-devices-Attendee-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-click-more-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-attendee-click-more-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-devices-Attendee-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/RoomsCallScreen.test.ts-snapshots/rooms-call-screen-devices-Attendee-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/CustomDataModel.test.ts-snapshots/custom-data-model-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/CustomDataModel.test.ts-snapshots/custom-data-model-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/CustomDataModel.test.ts-snapshots/custom-data-model-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/Messaging.test.ts-snapshots/one-message-in-chat-thread-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/chat/hermetic/ReadReceipt.test.ts-snapshots/sent-messages-Mobile-Android-Portrait-linux.png
  packages/storybook8/package.json
  rush.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
  samples/tests/snapshots/stable/StaticHtmlComposites/CompositeJavascriptTest.test.ts-snapshots/chatCompositeHtmlCheck-chromium-linux.png
Labels: does not need changelog, significant bundle size change

#5548 Prerelease stable remove beta suffix/1.23.0
  change/@azure-communication-react-02e14d41-7b7c-4a6f-9612-c1396c8e098e.json
  change/@azure-communication-react-05df919a-0892-4766-8264-47a1ada378c7.json
  change/@azure-communication-react-0ada3974-ba3c-4edd-921a-621f11616e23.json
  change/@azure-communication-react-14337074-c277-4f01-a462-ee2273c43089.json
  change/@azure-communication-react-1502fd01-ef0d-489a-a99d-6946fc4e9258.json
  change/@azure-communication-react-31153022-b68a-433b-87c3-d55c675d6e37.json
  change/@azure-communication-react-34244f58-3cf8-44b0-9484-8a89802eff66.json
  change/@azure-communication-react-452e1c29-f562-491d-bd4a-7d9d58cb3778.json
  change/@azure-communication-react-4c3df59a-c10e-43da-b10a-aa82d87c0f11.json
  change/@azure-communication-react-57cd7723-5d5c-42b4-bbf0-c9c839448d49.json
  change/@azure-communication-react-770df296-e84b-4925-9152-a8832b309a65.json
  change/@azure-communication-react-84f1f7b4-4854-4450-9214-b4b3ec9c47d5.json
  change/@azure-communication-react-8f3f7c74-3500-4ecb-994e-9da8d77d415b.json
  change/@azure-communication-react-c0b634e9-dc8d-4ecb-9d78-940517f2f5dc.json
  change/@azure-communication-react-d8ba7749-9ddc-42f0-b17b-50765eeca2c8.json
  change/@azure-communication-react-e0342179-d573-4e63-bcd2-f76b8da9e4f3.json
  change/@azure-communication-react-f18ec6dc-7182-46e5-b744-2dc76436d44f.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.json
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5580 Real Time Text API update and tests
  change-beta/@azure-communication-react-4b0c972c-f310-493e-a96f-29df49eefadf.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/styles/Captions.style.ts
  packages/react-components/src/components/utils/sortCaptionsAndRealTimeTexts.test.ts
Labels: breaking-change

#5582 Updated the dependencies to fix security alerts
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-components/src/components/RichTextEditor/Plugins/PlaceholderPlugin.tsx
Labels: does not need changelog

#5586 Add expand button for mobile RTT and captions
  change-beta/@azure-communication-react-c93d7b33-4252-4b25-82b3-44c23230f486.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/styles/Captions.style.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-settings-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-settings-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/caption-toggle-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-settings-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-settings-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-caption-toggle-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Mobile-Android-Portrait-linux.png
Labels: significant bundle size change

#5587 Remove media access conditional compile - part 1
  change-beta/@azure-communication-react-cc9a918b-409e-4290-baa7-a73df9ef8032.json
  change/@azure-communication-react-cc9a918b-409e-4290-baa7-a73df9ef8032.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/CapabilitiesSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/MediaAccessSubscriber.ts
  packages/calling-stateful-client/src/StatefulCallClient.test.ts
  packages/calling-stateful-client/src/TestUtils.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
Labels: breaking-change

#5590 RTT Feature: Stateful and component binding layer API changes and adapters
  change-beta/@azure-communication-react-72804e5e-cf17-4d1b-8d4a-bbd6b22a1c26.json
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/RealTimeTextSubscriber.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/index.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/index.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/localization/locales/en-US/strings.json
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: breaking-change

#5583 Fix calling example links for Custom User Data Model Storybook page
  packages/storybook8/stories/Concepts/CustomUserDataModel/Docs.mdx
Labels: does not need changelog

#5592 RTT Feature: Change id to sequence id
  change-beta/@azure-communication-react-19209e7d-098c-4cfc-b0e5-40636320691b.json
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/CaptionsBanner.tsx
Labels: breaking-change

#5593 RTT Feature Storybook
  change-beta/@azure-communication-react-bb8f9249-1983-497f-a7b5-e49bc5bc2d2b.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/StartRealTimeTextButton.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/storybook8/public/images/CaptionsBannerRTT.png
  packages/storybook8/public/images/RTTModal.png
  packages/storybook8/public/images/StartRTT.png
  packages/storybook8/stories/Components/CaptionsBanner/CaptionsBanner.story.tsx
  packages/storybook8/stories/Components/CaptionsBanner/Docs.mdx
  packages/storybook8/stories/Components/CaptionsBanner/index.stories.tsx
  packages/storybook8/stories/Components/CaptionsBanner/mockCaptions.ts
  packages/storybook8/stories/Components/CaptionsSettingsModal/Docs.mdx
  packages/storybook8/stories/Components/RealTimeText/Docs.mdx
  packages/storybook8/stories/Components/RealTimeText/RealTimeText.story.tsx
  packages/storybook8/stories/Components/RealTimeText/index.stories.tsx
  packages/storybook8/stories/Components/RealTimeText/snippets/ExampleRealTimeText.snippet.tsx
  packages/storybook8/stories/Components/RealTimeTextModal/Docs.mdx
  packages/storybook8/stories/Components/RealTimeTextModal/RealTimeTextModal.story.tsx
  packages/storybook8/stories/Components/RealTimeTextModal/index.stories.tsx
  packages/storybook8/stories/Components/RealTimeTextModal/snippets/RealTimeTextModal.snippet.tsx
  packages/storybook8/stories/Components/StartCaptionsButton/index.stories.tsx
  packages/storybook8/stories/Components/StartRealTimeTextButton/Docs.mdx
  packages/storybook8/stories/Components/StartRealTimeTextButton/StartRealTimeTextButton.story.tsx
  packages/storybook8/stories/Components/StartRealTimeTextButton/index.stories.tsx
  packages/storybook8/stories/Components/StartRealTimeTextButton/snippets/StartRealTimeTextButton.snippet.tsx
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
  packages/storybook8/stories/Concepts/ClosedCaptions/Doc.mdx
  packages/storybook8/stories/Concepts/RealTimeText/Docs.mdx
  packages/storybook8/stories/controlsUtils.ts
Labels: breaking-change

#5589 Updated Node versions for Web UI library
  .github/workflows/alpha-release.yml
  .github/workflows/create-api-view-feature-level.yml
  .github/workflows/create-prerelease-branch.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/deploy-azure-webapps.yml
  .github/workflows/deploy-feature-azure-webapps.yml
  .github/workflows/deploy-release-azure-webapps.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/nightly-cd.yml
  .github/workflows/npm-release-publish.yml
  .github/workflows/publish-chromatic.yml
  .github/workflows/stress-test-ui-tests.yml
  .github/workflows/update-api-files.yml
  .github/workflows/update-chat-snapshots.yml
  .github/workflows/update-snapshots.yml
  packages/react-components/tests/browser/FluentChatMessageComponentKeyboardNavigationTests.spec.tsx
Labels: does not need changelog

#5598 Storybook Update: Captions Banner snippet
  packages/storybook8/stories/Components/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
Labels: does not need changelog

#5602 Remove HMR causing codespace to not load samples correctly
  common/config/webpack/sampleapp.webpack.config.js
  samples/Server/package.json
Labels: does not need changelog

#5594 Remove hard mute conditional compile - part 3
  change-beta/@azure-communication-react-b6480f7d-32ed-4b4e-a3dd-d73a0d0bd12c.json
  change/@azure-communication-react-b6480f7d-32ed-4b4e-a3dd-d73a0d0bd12c.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/LocalVideoTile.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/ParticipantItem.tsx
  packages/react-components/src/components/ParticipantList.tsx
  packages/react-components/src/components/RemoteVideoTile.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/LocalScreenShare.tsx
  packages/react-components/src/components/VideoGallery/useVideoStreamLifecycleMaintainer.ts
  packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/ParticipantListParticipant.ts
  packages/react-components/src/types/VideoGalleryParticipant.ts
Labels: breaking-change

#5581 Enable together mode for mobile
  packages/react-components/src/components/TogetherModeOverlay.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/TogetherModeLayout.tsx
  packages/react-components/src/components/VideoGallery/TogetherModeStream.tsx
  packages/react-components/src/components/styles/TogetherMode.styles.ts
  packages/react-components/src/index.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/default-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5601 Dependencies update
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5606 Updated playwright dependencies
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-components/package.json
  packages/react-composites/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5603 Remove conditional compile for media access - Part 4
  change-beta/@azure-communication-react-01ee9977-a348-46bc-b8c3-3a6efd208cf2.json
  change/@azure-communication-react-01ee9977-a348-46bc-b8c3-3a6efd208cf2.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/LocalVideoTile.tsx
  packages/react-components/src/components/VideoTile.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/types/ParticipantListParticipant.ts
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/CapabilitiesChangedNotificationBar.tsx
  packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/tests/browser/call/hermetic/MediaAccess.test.ts
  packages/react-composites/tests/browser/call/hermetic/VideoGalleryLayout.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: breaking-change
