Repository Azure/communication-ui-library, pull requests merged in 2025-05, with the labels that each got.

#5813 Remove Beta Banner for RTT
  packages/storybook8/stories/Components/CaptionsBanner/Docs.mdx
  packages/storybook8/stories/Components/RealTimeText/Docs.mdx
  packages/storybook8/stories/Components/RealTimeTextModal/Docs.mdx
  packages/storybook8/stories/Components/StartRealTimeTextButton/Docs.mdx
  packages/storybook8/stories/Concepts/RealTimeText/Docs.mdx
Labels: does not need changelog

#5816 Remove RTT cc line
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/captionsSelector.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/RealTimeTextSubscriber.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RTTDisclosureBanner.tsx
  packages/react-components/src/components/RealTimeText.tsx
  packages/react-components/src/components/RealTimeTextModal.tsx
  packages/react-components/src/components/StartRealTimeTextButton.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/components/styles/Captions.style.ts
  packages/react-components/src/components/styles/RTTDisclosureBanner.styles.ts
  packages/react-components/src/components/utils/sortCaptionsAndRealTimeTexts.test.ts
  packages/react-components/src/components/utils/sortCaptionsAndRealTimeTexts.tsx
  packages/react-components/src/localization/LocalizationProvider.tsx
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/index.ts
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/index.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx
  packages/react-composites/src/composites/common/CallingRealTimeTextModal.tsx
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/Drawer/PreparedMoreDrawer.tsx
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/RealTimeText.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/RealTimeText.test.ts
  packages/react-composites/tests/browser/common/constants.ts
  samples/CallingStateful/src/components/CallingComponents.tsx
Labels: does not need changelog

#5819 Fix storybook link for custom data model
  packages/storybook8/stories/Composites/CallComposite/Docs.mdx
Labels: does not need changelog

#5824 Ensures component re-renders when isReceiving flag updates
  packages/react-components/src/components/VideoGallery/TogetherModeStream.tsx
Labels: does not need changelog

#5826 Promote together mode to GA
  change-beta/@azure-communication-react-c86b183b-185c-4dcd-b26d-5d512109b5a7.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-hidden-in-acs-call-Desktop-Chrome-linux.png
Labels: breaking-change

#5828 Updated playwright dependencies
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-components/package.json
  packages/react-components/playwright.config.components.ts
  packages/react-composites/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: does not need changelog

#5830 Stable SDK update
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/TypeAssertions.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change, does not need changelog

#5832 Updated dependencies
  common/config/package.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog, significant bundle size change

#5851 [Bugfix] update docs to fix disposal issue
  packages/storybook8/stories/Composites/TypeScriptLoading/Docs.mdx
Labels: does not need changelog

#5856 Revert a11y dropdown group announcement
  change-beta/@azure-communication-react-4b170639-a671-4920-b5d6-0f5348f02b5f.json
  change-beta/@azure-communication-react-dddcb5df-0075-426b-8012-314e9c29ae97.json
  packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx
Labels: does not need changelog

#5858 Update release version for 1.27.1
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-common/src/telemetryVersion.js
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5854 remove conditional compile flags for together mode feature
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallFeatureStreamUtils.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/Converter.ts
  packages/calling-stateful-client/src/InternalCallContext.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/calling-stateful-client/src/StreamUtils.test.ts
  packages/calling-stateful-client/src/StreamUtils.ts
  packages/calling-stateful-client/src/TogetherModeSubscriber.ts
  packages/calling-stateful-client/src/TogetherModeVideoStreamSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/src/index.ts
  packages/react-components/src/components/MeetingReactionOverlay.tsx
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/TogetherModeOverlay.test.tsx
  packages/react-components/src/components/TogetherModeOverlay.tsx
  packages/react-components/src/components/VideoGallery.test.tsx
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/Layout.ts
  packages/react-components/src/components/VideoGallery/TogetherModeLayout.tsx
  packages/react-components/src/components/VideoGallery/TogetherModeStream.tsx
  packages/react-components/src/components/styles/TogetherMode.styles.ts
  packages/react-components/src/components/utils.ts
  packages/react-components/src/index.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-components/src/types/ReactionTypes.ts
  packages/react-components/src/types/TogetherModeTypes.ts
  packages/react-components/src/types/index.ts
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/src/composites/common/icons.tsx
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/TogetherModeOverlay.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: does not need changelog

#5859 Add a new Stroybook page for AdaptiveCard
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/storybook8/package.json
  packages/storybook8/stories/Components/MessageThread/MessageWithAdaptiveCard/CustomizedAdaptiveCardMessage.story.tsx
  packages/storybook8/stories/Components/MessageThread/MessageWithAdaptiveCard/Docs.mdx
  packages/storybook8/stories/Components/MessageThread/MessageWithAdaptiveCard/index.stories.tsx
  packages/storybook8/stories/Components/MessageThread/MessageWithAdaptiveCard/snippets/MessageWithAdaptiveCard.snippet.tsx
  packages/storybook8/stories/Components/MessageThread/snippets/placeholdermessages.ts
Labels: does not need changelog

#5870 Modular ESLint configuration
  common/config/ESLint/eslint.config.ts
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/eslint.config.js
  packages/acs-ui-common/eslint.config.ts
  packages/acs-ui-common/package.json
  packages/acs-ui-common/src/safeStringify.ts
  packages/react-composites/src/composites/CallComposite/pages/DtmfDialpadPage.tsx
Labels: does not need changelog

#5873 Merge back Prerelease beta release beta/1.28.0 beta.1
  change-beta/@azure-communication-react-04498cb3-719d-4807-ba50-8357f4347c42.json
  change-beta/@azure-communication-react-084cf838-5048-4091-87b4-678136af0aad.json
  change-beta/@azure-communication-react-231c0a17-7d2b-4688-8543-8e193e4ec533.json
  change-beta/@azure-communication-react-271f62f9-a1f3-49ea-98d7-990632f218f2.json
  change-beta/@azure-communication-react-325e6ec7-6ec7-42b8-a864-835bbef4bb8e.json
  change-beta/@azure-communication-react-36a1a63f-4e47-49ba-a9ef-7cee18d8b66d.json
  change-beta/@azure-communication-react-5383523c-098f-451f-a179-6625b3e9a021.json
  change-beta/@azure-communication-react-5dd68808-eeba-4ab6-b68e-e66c77aad1ce.json
  change-beta/@azure-communication-react-60dbc1f9-ed82-4344-b568-d0030c7be6a6.json
  change-beta/@azure-communication-react-866200b1-cae4-404a-b452-82a33f1cefb3.json
  change-beta/@azure-communication-react-8c58c3e1-000c-452f-b51a-33cc3be306ee.json
  change-beta/@azure-communication-react-9651a2f5-ed87-4aed-9132-a89dc4f6931d.json
  change-beta/@azure-communication-react-972e4629-8efc-4aee-9d2f-1cd2c2a67243.json
  change-beta/@azure-communication-react-a464af95-227c-47d9-9d03-d3410f68c0f8.json
  change-beta/@azure-communication-react-a92929a6-ab58-41fb-97d6-a37daf033059.json
  change-beta/@azure-communication-react-b65c3dd0-9eb5-463f-a8e6-ad368c3b447b.json
  change-beta/@azure-communication-react-b9764b6e-345a-48c3-bef7-797fe4550e76.json
  change-beta/@azure-communication-react-c86b183b-185c-4dcd-b26d-5d512109b5a7.json
  change-beta/@azure-communication-react-d007e34c-cd16-4d26-a95f-ea4a45a4ca7c.json
  change-beta/@azure-communication-react-d44320f8-4979-4572-87c6-b666454a9377.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5871 Updated chat examples for UseSelector Storybook page
  packages/chat-component-bindings/src/handlers/createHandlers.test.ts
  packages/chat-component-bindings/src/handlers/createHandlers.ts
  packages/storybook8/stories/StatefulClient/ReactHooks/UseSelector.mdx
Labels: does not need changelog
