Repository Azure/communication-ui-library, pull requests merged in 2025-04, with the labels that each got.

#5751 [Notifications] hide notification
  change-beta/@azure-communication-react-bad3f807-0932-4766-8415-842ed93cb4f7.json
  change/@azure-communication-react-bad3f807-0932-4766-8415-842ed93cb4f7.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/index.ts
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/storybook8/stories/controlsUtils.ts
Labels: breaking-change, significant bundle size change

#5760 [Notifications] fix naming typo with notification icon name
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
Labels: breaking-change, does not need changelog

#5759 Fix typo in use cases storybook page
  packages/storybook8/stories/UseCases.mdx
Labels: does not need changelog

#5709 Remove conditional compilation for breakout rooms feature
  common/config/babel/features.js
  packages/calling-component-bindings/src/baseSelectors.ts
  packages/calling-component-bindings/src/notificationStackSelector.ts
  packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/CallContext.ts
  packages/calling-stateful-client/src/CallSubscriber.ts
  packages/calling-stateful-client/src/index-public.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/components/utils.ts
  packages/react-components/src/theming/icons.tsx
  packages/react-composites/src/composites/CallComposite/CallComposite.tsx
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/Strings.tsx
  packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallComposite/components/BreakoutRoomsBanner.tsx
  packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
  packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
  packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
  packages/react-composites/src/composites/CallComposite/hooks/useCompositeStringsForNotificationStack.ts
  packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
  packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
  packages/react-composites/src/composites/CallComposite/utils/Utils.ts
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.test.tsx
  packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
  packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts
  packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
  packages/react-composites/src/composites/CallWithChatComposite/styles/CallWithChatCompositeStyles.ts
  packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
  packages/react-composites/src/composites/common/adapters.ts
  packages/react-composites/src/composites/common/utils.tsx
  packages/react-composites/src/composites/index.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
Labels: does not need changelog

#5762 RTT Hermetic tests
  packages/react-components/src/components/CaptionsBanner.tsx
  packages/react-components/src/components/RealTimeTextModal.tsx
  packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
  packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx
  packages/react-composites/tests/browser/call/hermetic/RealTimeText.test.ts
  packages/react-composites/tests/browser/callwithchat/hermetic/RealTimeText.test.ts
  packages/react-composites/tests/browser/common/constants.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-modal-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-button-call-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-modal-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/rtt-disabled-toggle-button-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Mobile-Android-Portrait-linux.png
Labels: does not need changelog

#5766 [release 1.26.0] Groom changelog stable remove beta suffix/1.26.0
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#5763 [bugfix] release action permissions
  .github/workflows/create-prerelease-branch.yml
  .github/workflows/create-release-branch.yml
Labels: does not need changelog

#5729 [onFetchProfile] Add onFetchProfile for CallWithChat composite
  change-beta/@azure-communication-react-f46db66c-1ff6-45c5-ab56-f6c6c066261c.json
  change/@azure-communication-react-f46db66c-1ff6-45c5-ab56-f6c6c066261c.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.test.ts
  packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
  packages/react-composites/src/composites/ChatComposite/adapter/OnFetchProfileCallback.ts
  packages/react-composites/src/composites/ChatComposite/index.ts
Labels: breaking-change

#5773 [Release] update calling effects 1.1.4
  change-beta/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json
  change/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
Labels: significant bundle size change

#5768 Update creating-a-release.md to include step 0.0
  docs/releases/creating-a-release.md
Labels: does not need changelog

#5778 Cherry pick stable PR into release branch
  common/config/jest/jestSetup.js
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: update_snapshots

#5783 TDBuild latest localization
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: does not need changelog

#5767 Prerelease stable remove beta suffix/1.26.0
  change/@azure-communication-react-1656d4b5-c12e-4210-a04f-ff68329560e7.json
  change/@azure-communication-react-20731bca-4cc9-4582-8733-a93acdce9124.json
  change/@azure-communication-react-38bd8537-9167-4bee-818d-e0da918622dd.json
  change/@azure-communication-react-6d0bac59-3894-4586-aaa0-ee9b817fcee7.json
  change/@azure-communication-react-876f80cc-fe37-43ca-8af5-93b7118ab9fa.json
  change/@azure-communication-react-bad3f807-0932-4766-8415-842ed93cb4f7.json
  change/@azure-communication-react-f3b8f974-0cf7-40ff-9a59-316682f8a3e4.json
  change/@azure-communication-react-f68338ad-fc4f-463e-b91a-4a6d648986d7.json
  change/@azure-communication-react-ff396efc-ebbc-4789-b224-c84d00abbaf8.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.json
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5786 TDBuild latest localization
  packages/react-components/src/localization/locales/ar-SA/strings.json
  packages/react-components/src/localization/locales/cs-CZ/strings.json
  packages/react-components/src/localization/locales/cy-GB/strings.json
  packages/react-components/src/localization/locales/de-DE/strings.json
  packages/react-components/src/localization/locales/en-GB/strings.json
  packages/react-components/src/localization/locales/es-ES/strings.json
  packages/react-components/src/localization/locales/es-MX/strings.json
  packages/react-components/src/localization/locales/fi-FI/strings.json
  packages/react-components/src/localization/locales/fr-CA/strings.json
  packages/react-components/src/localization/locales/fr-FR/strings.json
  packages/react-components/src/localization/locales/he-IL/strings.json
  packages/react-components/src/localization/locales/it-IT/strings.json
  packages/react-components/src/localization/locales/ja-JP/strings.json
  packages/react-components/src/localization/locales/ko-KR/strings.json
  packages/react-components/src/localization/locales/nb-NO/strings.json
  packages/react-components/src/localization/locales/nl-NL/strings.json
  packages/react-components/src/localization/locales/pl-PL/strings.json
  packages/react-components/src/localization/locales/pt-BR/strings.json
  packages/react-components/src/localization/locales/ru-RU/strings.json
  packages/react-components/src/localization/locales/sv-SE/strings.json
  packages/react-components/src/localization/locales/tr-TR/strings.json
  packages/react-components/src/localization/locales/zh-CN/strings.json
  packages/react-components/src/localization/locales/zh-TW/strings.json
Labels: does not need changelog, significant bundle size change

#5801 Addressed overflow comment
  packages/react-components/src/components/TogetherModeOverlay.tsx
Labels: does not need changelog

#5804 1.27.0-beta.1 changelog
  packages/communication-react/CHANGELOG.beta.md
Labels: does not need changelog

#5805 Update snapshots in 1.27.0-beta.1 branch
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-hidden-in-acs-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-meeting-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/default-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-controls-open-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Landscape-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/gallery-options-mobile-Mobile-Android-Portrait-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/VideoGallery.test.ts-snapshots/speaker-layout-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/ClosedCaptions.test.ts-snapshots/show-captions-RTL-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/realTimeText-banner-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/RealTimeText.test.ts-snapshots/show-realTimeText-caption-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/show-teams-captions-RTL-Desktop-Chrome-linux.png
  samples/tests/snapshots/beta/StaticHtmlComposites/CompositeJavascriptTest.test.ts-snapshots/chatCompositeHtmlCheck-chromium-linux.png
Labels: does not need changelog
