Repository Azure/communication-ui-library, pull requests merged in 2025-07, with the labels that each got.

#5917 Remove console log around default mic device
  packages/react-components/src/components/DevicesButton.tsx
Labels: does not need changelog

#5916 [A11y] Add aria-label for upload progress
  change-beta/@azure-communication-react-a9d5fe68-a874-4d68-bef5-a3a814c33298.json
  change/@azure-communication-react-a9d5fe68-a874-4d68-bef5-a3a814c33298.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/react-components/src/components/Attachment/AttachmentCard.tsx
  packages/react-components/src/components/Attachment/AttachmentUploadCards.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/SendBox.tsx
  packages/react-components/src/components/utils/common.ts
  packages/react-components/src/localization/locales/en-US/strings.json
Labels: breaking-change

#5919 update docs for cleaning up our adapters
  packages/storybook8/stories/Composites/Adapters/Docs.mdx
Labels: does not need changelog

#5931 Fix together mode local label (Cherry pick #5927)
  packages/communication-react/CHANGELOG.stable.md
  packages/react-components/src/components/TogetherModeOverlay.tsx
Labels: does not need changelog

#5932 Merge 1.29.0 prerelease branch back to main
  change/@azure-communication-react-05227330-4bee-42f1-a6a1-c9a2c7158ba5.json
  change/@azure-communication-react-260b0b2c-c155-4a4a-9dd1-853630f6ee16.json
  change/@azure-communication-react-30383b0f-18e4-4760-9498-eb295d5b0ee5.json
  change/@azure-communication-react-34f07369-28bb-4798-8778-64aaf8da54d1.json
  change/@azure-communication-react-3b217966-05f7-414a-8d89-bde966b9287b.json
  change/@azure-communication-react-5594f302-84ab-4d5e-8589-853e8ffe6005.json
  change/@azure-communication-react-59be0ba8-2007-4ade-bf4f-6edeb0f7ce4c.json
  change/@azure-communication-react-5ba500e8-02ff-44d6-b74d-94431cd7383f.json
  change/@azure-communication-react-693cf971-464a-42cc-a268-8732e49959bf.json
  change/@azure-communication-react-8b8d32d3-698c-4073-9829-9b510c05fe4e.json
  change/@azure-communication-react-9e983c64-11ee-4c3d-8bd6-018e462fe5c3.json
  change/@azure-communication-react-a9d5fe68-a874-4d68-bef5-a3a814c33298.json
  change/@azure-communication-react-bc1dcafa-7978-478d-bf3e-22f4d211eab0.json
  change/@azure-communication-react-cadd1df4-cd5c-458c-a027-e4bcdd9260d7.json
  change/@azure-communication-react-ef5bbe3d-7258-40db-bf56-221083d1a0fa.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.json
  packages/communication-react/CHANGELOG.stable.md
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog

#5934 Update Storybook Quickstarts page link in README.md
  README.md
Labels: does not need changelog

#5939 [AudioContext] Add new logger for the composite and add log lines for audio context
  change-beta/@azure-communication-react-31c7fd68-c556-460d-802c-c22af3d41159.json
  change/@azure-communication-react-31c7fd68-c556-460d-802c-c22af3d41159.json
  common/config/jest/jestSetup.js
  packages/react-composites/src/composites/common/AudioProvider.tsx
  packages/react-composites/src/composites/common/BaseComposite.tsx
  packages/react-composites/src/composites/common/logger.ts
  packages/storybook8/stories/Concepts/Troubleshooting/Docs.mdx
Labels: significant bundle size change

#5948 Axios version update
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  samples/Chat/package.json
Labels: does not need changelog

#5950 Updated remaining axios dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
Labels: does not need changelog

#5955 Update dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  docs/agent/dependency-management-guide.md
Labels: does not need changelog
