Repository Azure/communication-ui-library, pull requests merged in 2025-06, with the labels that each got.

#5884 Groom changelog stable remove beta suffix/1.28.0
  packages/communication-react/CHANGELOG.stable.md
Labels: does not need changelog

#5886 [A11y] Add error message for empty content for edit box
  change-beta/@azure-communication-react-8b8d32d3-698c-4073-9829-9b510c05fe4e.json
  change/@azure-communication-react-8b8d32d3-698c-4073-9829-9b510c05fe4e.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBox.tsx
  packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
  packages/react-components/src/components/MessageThread.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.test.tsx
  packages/react-components/src/components/RichTextEditor/RichTextSendBoxErrors.tsx
  packages/react-components/src/components/utils/ChatMessageComponentAsEditBoxUtils.tsx
  packages/react-components/src/localization/locales/en-US/strings.json
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-edit-box-empty-content-without-attachment-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-edit-box-empty-content-without-attachment-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-edit-box-empty-content-without-attachment-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-content-without-attachment-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-content-without-attachment-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-content-without-attachment-Mobile-Android-Portrait-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-html-content-without-attachment-Desktop-Chrome-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-html-content-without-attachment-Mobile-Android-Landscape-linux.png
  packages/react-components/tests/snapshots/beta/ChatMyMessageComponent.spec.tsx-snapshots/chat-my-message-component-rich-text-edit-box-empty-html-content-without-attachment-Mobile-Android-Portrait-linux.png
Labels: breaking-change

#5891 Update webpack-dev-server to 5.2.2
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-composites/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
Labels: does not need changelog

#5894 Update multer to latest (2.0.1)
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  samples/Server/package.json
Labels: does not need changelog

#5909 [OCE] calling sdk 1.36.1
  common/config/rush/variants/stable/common-versions.json
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/calling-stateful-client/src/CallClientState.ts
  packages/calling-stateful-client/src/StatefulCallClient.ts
  packages/communication-react/package.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  samples/tests/package.json
Labels: breaking-change, does not need changelog
