Repository Azure/communication-ui-library, pull requests merged in 2025-03, with the labels that each got.

#5680 Update dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/communication-react/review/stable/communication-react.api.md
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/Server/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
Labels: does not need changelog

#5682 Update Express to v5
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/react-composites/package.json
  samples/Server/package.json
  samples/Server/src/routes/issueToken.ts
  samples/tests/package.json
Labels: does not need changelog

#5691 [BugFix] Remove node versions from storybook
  packages/storybook8/stories/Components/GettingStarted/Docs.mdx
  packages/storybook8/stories/Composites/GettingStarted.mdx
  packages/storybook8/stories/Setup.mdx
  packages/storybook8/stories/StatefulClient/Call/Docs.mdx
  packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Labels: does not need changelog

#5658 Together mode e2e testcases
  packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
  packages/react-composites/tests/app/lib/MockCallAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/TogetherModeOverlay.test.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/common/constants.ts
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-participant-1-click-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-icons-only-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-mute-icon-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-hidden-in-acs-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-meeting-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-raisehand-icon-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-spotlight-icon-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/beta/tests/browser/callwithchat/hermetic/TeamsClosedCaptions.test.ts-snapshots/teams-captions-with-chat-pane-Desktop-Chrome-linux.png
Labels: does not need changelog

#5705 Update axios to 1.8.2
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  samples/Chat/package.json
Labels: does not need changelog

#5708 Update node-forge to 1.3.1
  packages/communication-react/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
Labels: does not need changelog

#5644 [OCE updates] update calling-effects
  .github/workflows/touchdown-pipeline/touchdown-build.yml
  change-beta/@azure-communication-react-239abcdd-a3f4-40a8-8eda-f33969a29e0d.json
  change/@azure-communication-react-239abcdd-a3f4-40a8-8eda-f33969a29e0d.json
  common/config/rush/common-versions.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/common-versions.json
  packages/calling-component-bindings/package.json
  packages/communication-react/package.json
  packages/react-composites/package.json
Labels: significant bundle size change

#5711 Promote together mode to stable
  change-beta/@azure-communication-react-0bc61add-56be-450e-b76c-7055ee2b919d.json
  change-beta/@azure-communication-react-7fea4da2-61eb-41c5-9733-48ea5e25a3a3.json
  change-beta/@azure-communication-react-86715e14-10d5-4a70-9e2e-048c3523cc0a.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
  packages/calling-stateful-client/src/CallClientState.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/NotificationStack.tsx
  packages/react-components/src/types/TogetherModeTypes.ts
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
  packages/react-composites/tests/browser/call/hermetic/fixture.ts
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-participant-1-click-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-icons-only-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-mute-icon-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-all-participants-in-smaller-size-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-hidden-in-acs-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-call-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-option-in-teams-meeting-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-raisehand-icon-Desktop-Chrome-linux.png
  packages/react-composites/tests/browser/snapshots/stable/tests/browser/call/hermetic/TogetherModeOverlay.test.ts-snapshots/together-mode-view-spotlight-icon-Desktop-Chrome-linux.png
Labels: breaking-change

#5716 [OCE] update babel
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/package.json
  packages/communication-react/package.json
  packages/fake-backends/package.json
  packages/react-components/package.json
  packages/react-composites/package.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/package.json
Labels: does not need changelog

#5723 Fixed an issue with types for usePropsFor
  change-beta/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
  change/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/mergedHooks.ts
Labels: breaking-change

#5726 Revert "Fixed an issue with types for usePropsFor"
  change-beta/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
  change/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/mergedHooks.ts
Labels: breaking-change, does not need changelog

#5728 Revert "specific usePropsFor to treeshake out unncessary calling/chat code"
  change-beta/@azure-communication-react-2e4a29d5-272c-4225-9f4f-add54c5646f1.json
  change-beta/@azure-communication-react-4a805157-c696-47df-8490-c10e6c9370f2.json
  change-beta/@azure-communication-react-bc219d8c-b452-49b5-b84d-fda5e16c9e1f.json
  change/@azure-communication-react-2e4a29d5-272c-4225-9f4f-add54c5646f1.json
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/communication-react/src/mergedHooks.ts
  packages/storybook8/stories/StatefulClient/BestPractices.mdx
Labels: breaking-change, does not need changelog

#5718 Storybook dependencies update
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  packages/storybook8/package.json
Labels: does not need changelog

#5735 Groom changelog beta release beta/1.26.0 beta.1
  packages/communication-react/CHANGELOG.beta.md
Labels: does not need changelog

#5732 Update axios to 1.8.4
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/stable/pnpm-lock.yaml
  samples/Chat/package.json
Labels: does not need changelog, significant bundle size change

#5738 [A11y][Chat sample] Add tooltip for Leave Chat button in Chat sample
  samples/Chat/src/app/ChatHeader.tsx
Labels: does not need changelog

#5742 Revert back to beta in main
  change-beta/@azure-communication-react-f284b77c-7245-43ab-a075-70286742e975.json
  common/config/babel/features.js
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
Labels: breaking-change

#5746 Minor fixes for storybook pages
  packages/storybook8/stories/Composites/GettingStarted.mdx
  packages/storybook8/stories/StatefulClient/BestPractices.mdx
  packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Labels: does not need changelog

#5748 [Cherry-pick] Minor fixes for storybook pages
  packages/storybook8/stories/Composites/GettingStarted.mdx
  packages/storybook8/stories/StatefulClient/BestPractices.mdx
  packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Labels: does not need changelog

#5747 Together mode cherry picks to release/1.26.0-beta.1
  change-beta/@azure-communication-react-f284b77c-7245-43ab-a075-70286742e975.json
  common/config/babel/features.js
  packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
  packages/calling-component-bindings/src/videoGallerySelector.ts
  packages/communication-react/review/beta/communication-react.api.md
  packages/communication-react/review/stable/communication-react.api.md
  packages/react-components/src/components/VideoGallery.tsx
  packages/react-components/src/components/VideoGallery/TogetherModeStream.tsx
  packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
  packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
Labels: does not need changelog

#5743 Update storybook to include screenshare option documentation
  packages/storybook8/public/images/callcomposite-screenshare-default.png
  packages/storybook8/public/images/callcomposite-screenshare-legacy.png
  packages/storybook8/public/images/callcomposite-screenshare-recursive.png
  packages/storybook8/stories/Composites/CallComposite/Docs.mdx
  packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
Labels: does not need changelog

#5752 Merge prerelease branch for 1.26.0 beta.1 back to main
  change-beta/@azure-communication-react-0bc61add-56be-450e-b76c-7055ee2b919d.json
  change-beta/@azure-communication-react-11ff780a-f45b-4d87-aa95-1ce887a63d91.json
  change-beta/@azure-communication-react-2391dbc0-f978-47bd-bdb0-74d5b222f1ef.json
  change-beta/@azure-communication-react-239abcdd-a3f4-40a8-8eda-f33969a29e0d.json
  change-beta/@azure-communication-react-2486d3fd-5b86-4ae4-ada4-bca3f53046fb.json
  change-beta/@azure-communication-react-3d93404e-3923-46bb-8c8a-e8854a8860db.json
  change-beta/@azure-communication-react-424eb095-4b88-4a85-8ff5-888844a06236.json
  change-beta/@azure-communication-react-4572095b-9abd-4e6c-9b0b-25691874bf72.json
  change-beta/@azure-communication-react-45da9f59-d5f0-420c-a677-f6df8aa71cfd.json
  change-beta/@azure-communication-react-46abddf1-3c19-4736-a407-68e23b69a02e.json
  change-beta/@azure-communication-react-4b548d04-8071-4776-82e1-df52d49b442a.json
  change-beta/@azure-communication-react-4ebc3bfc-2026-4ee9-8d9d-8c0d80bc05a4.json
  change-beta/@azure-communication-react-7ce0977d-2176-4487-b23c-32fba99ce997.json
  change-beta/@azure-communication-react-7fea4da2-61eb-41c5-9733-48ea5e25a3a3.json
  change-beta/@azure-communication-react-86715e14-10d5-4a70-9e2e-048c3523cc0a.json
  change-beta/@azure-communication-react-a3709a74-d202-4af9-848d-9add1a8ff26f.json
  change-beta/@azure-communication-react-a6582b31-bc20-4f03-9520-efd5fb814b21.json
  change-beta/@azure-communication-react-ae4dd794-8396-42ec-b246-234e9dfc7214.json
  change-beta/@azure-communication-react-ddaf4d72-0b19-4712-a13b-e478b307039d.json
  change-beta/@azure-communication-react-e5646187-d63f-4c24-90d0-eafe141c850d.json
  change-beta/@azure-communication-react-f1119615-cc1f-466d-b6a2-36963f51adbe.json
  change-beta/@azure-communication-react-f3b8f974-0cf7-40ff-9a59-316682f8a3e4.json
  change-beta/@azure-communication-react-f665fa22-13e5-4587-ab70-779229c178cc.json
  change-beta/@azure-communication-react-fb5b6560-62cc-47f5-ae40-a8221afc67f4.json
  change-beta/@azure-communication-react-ff0dd21b-97d8-46f3-8ea2-c6218c50d480.json
  packages/acs-ui-common/package.json
  packages/acs-ui-javascript-loaders/CHANGELOG.json
  packages/acs-ui-javascript-loaders/package.json
  packages/calling-component-bindings/CHANGELOG.json
  packages/calling-component-bindings/package.json
  packages/calling-stateful-client/CHANGELOG.json
  packages/calling-stateful-client/package.json
  packages/chat-component-bindings/CHANGELOG.json
  packages/chat-component-bindings/package.json
  packages/chat-stateful-client/CHANGELOG.json
  packages/chat-stateful-client/package.json
  packages/communication-react/CHANGELOG.beta.md
  packages/communication-react/CHANGELOG.json
  packages/communication-react/package.json
  packages/fake-backends/CHANGELOG.json
  packages/fake-backends/package.json
  packages/react-components/CHANGELOG.json
  packages/react-components/package.json
  packages/react-composites/CHANGELOG.json
  packages/react-composites/package.json
  packages/storybook8/CHANGELOG.json
  packages/storybook8/package.json
  samples/CallWithChat/package.json
  samples/Calling/package.json
  samples/CallingStateful/package.json
  samples/Chat/package.json
  samples/ComponentExamples/package.json
  samples/StaticHtmlComposites/package.json
  tools/check-treeshaking/CHANGELOG.json
  tools/check-treeshaking/package.json
  tools/check-typescript-regression/CHANGELOG.json
  tools/check-typescript-regression/package.json
Labels: does not need changelog
